# LEAN-LLM-OPT

Generate and solve optimization models from natural-language questions and optional CSV data.

1. Configure project paths, OPENAI_API_KEY, and a Gurobi license.
2. Run the definition cells from top to bottom.
3. Enable an experiment at the end: automatic Large-scale-or, all six routes, or IndustryOR/another dataset.

Each experiment saves a small results.csv, per-case model.md / solve.py / solution.json files, and evaluation tables. Restart the kernel and rerun definitions after changing settings.

## 1. Imports and configuration

All Python dependencies and shared settings are defined here. OpenAI calls require an API key; solving requires a Gurobi license.

Required packages: openai, python-dotenv, gurobipy, numpy, pandas, ipython, langchain-classic, langchain-community, langchain-core, langchain-openai, and faiss-cpu.

In [104]:
from __future__ import annotations
import fcntl
import gurobipy as gp
import hashlib
import json
import math
import numpy as np
import os
import openai
import pandas as pd
import pprint
import re
import tempfile
from IPython.display import display
from dotenv import load_dotenv
from functools import lru_cache
from langchain_classic.agents import AgentType, Tool, initialize_agent
from langchain_classic.chains import LLMChain, RetrievalQA
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain_community.vectorstores import FAISS
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from pathlib import Path
from threading import RLock
from typing import Any
from urllib.parse import quote

In [105]:
# Start Jupyter in the repository root, or set LEAN_LLM_OPT_ROOT.
PROJECT_ROOT = Path(os.environ.get("LEAN_LLM_OPT_ROOT", Path.cwd())).expanduser().resolve()
BENCHMARK_PATH = PROJECT_ROOT / "Test_Dataset/Large-scale-or/Large-scale-or-101.csv"
OTHER_BENCHMARK_PATH = PROJECT_ROOT / "Test_Dataset/Small-scale/IndustryOR_fixedV2.csv"
RESULTS_DIR = PROJECT_ROOT / "outputs/large_scale_or_test_final"
NOTEBOOK_PATH = PROJECT_ROOT / "LEAN_LLM_OPT_4.1_Large-scale-or_V2.ipynb"

load_dotenv(PROJECT_ROOT / ".env.local", override=False)
load_dotenv(PROJECT_ROOT / ".env", override=False)
user_api_key = os.environ.get("OPENAI_API_KEY")

VERSION = "4.1-public"
MODEL_SNAPSHOT = "gpt-4.1-2025-04-14"
EMBEDDING_MODEL = "text-embedding-ada-002"
CLASS_LABELS = ["TP", "NRM", "RA", "FLP", "AP", "Mixture", "Others"]
WORKFLOW_ROUTES = ["TP", "NRM", "FLP", "AP", "RA", "Others"]
CSVQA_MODE_BY_ROUTE = {
    "NRM": "planned", "RA": "legacy", "TP": "legacy",
    "AP": "legacy", "FLP": "legacy", "Others": "legacy",
}
OTHERS_RAG_PATH = "Large_Scale_Or_Files/RAG_Example_Others.csv"

## 2. Shared model clients

All workflows use the configured model snapshot and output guard. Clients are created when requested.

In [106]:
class ModelOutputTruncated(RuntimeError):
    """The API explicitly reported an incomplete model response."""


class RejectTruncatedOutput(BaseCallbackHandler):
    raise_error = True

    def on_llm_end(self, response, **kwargs):
        for choices in response.generations:
            for generation in choices:
                metadata = getattr(getattr(generation, "message", None), "response_metadata", {}) or {}
                info = generation.generation_info or {}
                reason = str(info.get("finish_reason") or metadata.get("finish_reason") or "").lower()
                if reason in {"length", "max_tokens", "max_output_tokens"}:
                    error = ModelOutputTruncated(f"Model output is incomplete: finish_reason={reason}")
                    error.llm_usage = (response.llm_output or {}).get("token_usage", {})
                    raise error


def make_llm(*, timeout=180):
    return ChatOpenAI(
        model_name=MODEL_SNAPSHOT, openai_api_key=user_api_key,
        temperature=0.0, top_p=1, n=1, max_retries=0, timeout=timeout,
        callbacks=[RejectTruncatedOutput()],
    )


def make_embeddings():
    return OpenAIEmbeddings(model=EMBEDDING_MODEL, openai_api_key=user_api_key, max_retries=0)

## 3. CSV loading and route modes

Read CSV files, normalize routes, and select the fixed data-access mode. NRM uses planned extraction; the other routes use the legacy path.

In [107]:
def normalize_route(value: Any) -> str:
    text = str(value or "").strip().upper()
    aliases = {
        "NETWORK REVENUE MANAGEMENT": "NRM", "NETWORK REVENUE MANAGEMENT PROBLEM": "NRM",
        "RESOURCE ALLOCATION": "RA", "RESOURCE ALLOCATION PROBLEM": "RA",
        "TRANSPORTATION": "TP", "TRANSPORTATION PROBLEM": "TP",
        "ASSIGNMENT": "AP", "ASSIGNMENT PROBLEM": "AP",
        "FACILITY LOCATION": "FLP", "FACILITY LOCATION PROBLEM": "FLP",
    }
    text = aliases.get(text, text)
    if text in {"MIXTURE", "OTHER", "OTHERS"} or text.startswith("OTHERS"):
        return "Others"
    if text == "UFLP":
        return "FLP"
    if text in {"NRM", "RA", "TP", "AP", "FLP"}:
        return text
    raise ValueError(f"Unsupported execution route: {value!r}")


FILTER_OPERATORS = {
    "exact", "prefix", "contains", "in", "not_in", "eq", "ne",
    "gt", "ge", "lt", "le", "between", "is_null", "not_null",
}


FILTER_DTYPES = {"string", "number", "date"}


CSVQA_LEGACY_SYSTEM_PROMPT = (
    "Retrieve every CSV row needed by the query in source order. Preserve exact identifiers and "
    "numeric values. If the query names a subset, retrieve that complete subset; otherwise retrieve "
    "all data. Use only the supplied context: {context}"
)


CSVQA_LEGACY_TOOL_DESCRIPTION = (
    "Retrieve complete source-ordered CSV evidence needed to formulate the optimization problem."
)

def invoke_react_with_required_csvqa(agent, query, route):
    """Require CSVQA while preserving the existing ReAct agent boundary."""
    def call_count(result):
        return sum(
            isinstance(step, tuple)
            and len(step) >= 2
            and getattr(step[0], "tool", None) == "CSVQA"
            for step in result.get("intermediate_steps", [])
        )

    result = agent.invoke(query)
    if call_count(result) == 0:
        result = agent.invoke(
            "Protocol correction: call CSVQA before the Final Answer. Begin with Action: CSVQA.\n\n"
            f"User Description: {query}"
        )
    calls = call_count(result)
    planned = CSVQA_MODE_BY_ROUTE[normalize_route(route)] == "planned"
    if (planned or normalize_route(route) == "RA") and calls != 1:
        raise RuntimeError(f"{route} ReAct must call CSVQA exactly once; observed {calls}")
    if not planned and calls < 1:
        raise RuntimeError(f"{route} legacy ReAct must call CSVQA at least once; observed {calls}")
    return result


CSVQA_PLANNED_PROMPTS = {'NRM': 'Select every source row and column needed to define the revenue-management objective, decision entities, demand limits, inventory or capacity limits, and query-specific bounds. Infer exact columns from the query and schema. Filter only an explicit subset.'}

CSVQA_TOOL_DESCRIPTIONS = {'NRM': 'Return the canonical CSV rows, columns, filters, and relationships needed by the query.'}

def read_csv_compat(path, **kwargs):
    """Read a project-relative or absolute CSV with the requested pandas options."""
    path = Path(path).expanduser()
    path = path if path.is_absolute() else PROJECT_ROOT / path
    last_error = None
    for encoding in ("utf-8-sig", "utf-8", "gbk", "latin-1"):
        try:
            return pd.read_csv(path, encoding=encoding, **kwargs)
        except UnicodeDecodeError as exc:
            last_error = exc
    raise UnicodeError(f"Unable to decode CSV: {path}") from last_error


def _read_csv(path):
    """Read values as text and remove only empty structure or a clear export index."""
    frame = read_csv_compat(path, dtype=str, keep_default_na=False)
    frame.columns = [str(column).lstrip("\ufeff") for column in frame.columns]
    if frame.empty:
        return frame
    nonempty = frame.apply(lambda column: column.astype(str).str.strip().ne(""))
    frame = frame.loc[nonempty.any(axis=1), nonempty.any(axis=0)].copy()
    for column in list(frame.columns):
        values = frame[column].astype(str).tolist()
        sequential = values in (
            [str(i) for i in range(len(values))],
            [str(i) for i in range(1, len(values) + 1)],
        )
        if sequential and re.fullmatch(r"(?:unnamed(?::\s*\d+)?|index)", column.strip(), re.I):
            frame = frame.drop(columns=column)
    return frame


def _load_tables(dataset_address):
    """Resolve one-or-more newline-separated CSV paths in source order."""
    tables = []
    for raw in str(dataset_address or "").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        path = Path(raw).expanduser()
        path = path if path.is_absolute() else (PROJECT_ROOT / path).resolve()
        if not path.is_file():
            raise FileNotFoundError(f"CSVQA cannot find dataset file: {path}")
        tables.append({"file_index": len(tables), "path": path, "frame": _read_csv(path)})
    if not tables:
        raise ValueError("CSVQA requires at least one CSV path")
    return tables


def _build_profile(tables, query):
    """Expose schema, compact samples, and evidence for query-named terms."""
    quote_pattern = r'"([^\"]+)"|\'([^\']+)\'|“([^”]+)”|‘([^’]+)’'
    terms = list(dict.fromkeys(
        next(value for value in match.groups() if value is not None).strip()
        for match in re.finditer(quote_pattern, str(query or ""))
    ))
    key = lambda value: "".join(ch for ch in str(value or "").casefold() if ch.isalnum())
    profile = []
    for table in tables:
        frame = table["frame"]
        term_matches = {}
        for term in terms:
            wanted, value_matches = term.casefold(), {}
            for column in frame.columns:
                values = frame[column].astype(str).str.strip().str.casefold()
                counts = {
                    "exact": int(values.eq(wanted).sum()),
                    "prefix": int(values.str.startswith(wanted).sum()),
                    "contains": int(values.str.contains(wanted, regex=False).sum()),
                }
                if counts["contains"]:
                    value_matches[str(column)] = counts
            term_matches[term] = {
                "column_matches": [str(column) for column in frame.columns if key(column) == key(term)],
                "value_matches": value_matches,
            }
        profile.append({
            "file_index": table["file_index"],
            "file_name": table["path"].name,
            "rows": len(frame),
            "columns": list(frame.columns),
            "sample_values": {
                str(column): frame[column].astype(str).loc[lambda values: values.str.strip().ne("")]
                .drop_duplicates().head(4).tolist()
                for column in frame.columns
            },
            "query_terms": term_matches,
        })
    return profile

## 4. Planned CSV extraction

The model proposes columns and filters as JSON. Python applies the plan to the full CSV tables and preserves source identifiers and row order. These checks validate the data plan, not generated Python.

In [108]:
def _ask_extraction_plan(llm, route, query, tables, route_prompt):
    """Ask for one declarative plan and return the parsed plan plus raw response."""
    profile = json.dumps(_build_profile(tables, query), ensure_ascii=False)
    request = f"""You are a CSV extraction planner. Return one JSON object only.
Choose tables, columns, and filters from the user query and the supplied CSV profile. Do not return
data, Python, formulas, prose, joins, aggregation, sorting, sampling, or invented fields.

Shared plan schema:
{{"route":"{route}","tables":[{{"file_index":0,"role":"descriptive non-unique role",
"columns":["exact column"] or "*","filters":{{"logic":"and|or","conditions":[
{{"column":"exact column","operator":"exact|prefix|contains|in|not_in|eq|ne|gt|ge|lt|le|between|is_null|not_null",
"dtype":"string|number|date","value":"scalar or list","evidence":"exact query span",
"format":"optional date format","inclusive":"both|left|right|neither"}}]}}}}],
"ignored_file_indices":[],"relationships":[{{"type":"matrix",
"matrix_table_id":"file_2_view_0","row_id_column":"exact column",
"row_axis":{{"table_id":"file_0_view_0","id_column":"exact column"}},
"column_axis":{{"table_id":"file_1_view_0","id_column":"exact column"}}}}]}}

Python assigns each logical view a table_id of file_<file_index>_view_<zero-based occurrence for that
file>. A physical file may appear in multiple table specifications and roles may repeat. Every input
file must appear in tables or ignored_file_indices. Ignore a file only when the query does not need it.
Every explicit subset must have a filter and every filter must quote supporting query evidence.
Declare a matrix relationship only when the profile exposes its two axes unambiguously. When one label
column contains both decision entities and scalar parameter rows, retain every row that supplies a
query-required coefficient, price, cost, capacity, or bound; use separate logical views when helpful.

Route guidance:
{route_prompt}

User query:
{query}

CSV profile:
{profile}
"""
    text = str(llm.invoke([HumanMessage(content=request)]).content or "").strip()
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.I) if text.startswith("```") else text
    start, end = cleaned.find("{"), cleaned.rfind("}")
    if start < 0 or end < start:
        error = ValueError(f"CSVQA planner did not return a JSON object: {text[:200]}")
        error.planner_output = text
        raise error
    try:
        plan = json.loads(cleaned[start:end + 1])
    except ValueError as exc:
        error = ValueError(f"CSVQA planner returned invalid JSON: {exc}")
        error.planner_output = text
        raise error from exc
    if not isinstance(plan, dict):
        raise ValueError("CSVQA extraction plan must be a JSON object")
    return plan, text


def _apply_condition(series, condition):
    """Apply one allowlisted string, number, date, range, set, or null predicate."""
    operator, dtype = condition["operator"], condition.get("dtype", "string")
    raw, missing = series.astype(str).str.strip(), series.astype(str).str.strip().eq("")
    if operator in {"is_null", "not_null"}:
        return missing if operator == "is_null" else ~missing
    if dtype == "number":
        values, convert = pd.to_numeric(raw, errors="coerce"), float
    elif dtype == "date":
        date_format = condition.get("format") or None
        values = pd.to_datetime(raw, format=date_format, errors="coerce")
        convert = lambda value: pd.to_datetime(value, format=date_format)
    else:
        values = raw.str.casefold()
        convert = lambda value: str(value).strip().casefold()
    if dtype != "string" and values.loc[~missing].isna().any():
        raise ValueError(f"Cannot reliably parse {series.name!r} as {dtype}")
    value = condition.get("value")
    wanted = [convert(item) for item in value] if isinstance(value, list) else convert(value)
    if operator in {"in", "not_in", "between"} and not isinstance(wanted, list):
        raise ValueError(f"Operator {operator!r} requires a list value")
    if operator == "between" and len(wanted) != 2:
        raise ValueError("Operator 'between' requires exactly two bounds")
    operations = {
        "exact": lambda: values.eq(wanted), "eq": lambda: values.eq(wanted),
        "ne": lambda: values.ne(wanted) & ~missing,
        "prefix": lambda: values.str.startswith(wanted, na=False),
        "contains": lambda: values.str.contains(wanted, regex=False, na=False),
        "in": lambda: values.isin(wanted), "not_in": lambda: ~values.isin(wanted) & ~missing,
        "gt": lambda: values.gt(wanted), "ge": lambda: values.ge(wanted),
        "lt": lambda: values.lt(wanted), "le": lambda: values.le(wanted),
        "between": lambda: values.between(
            wanted[0], wanted[1], inclusive=condition.get("inclusive", "both")
        ),
    }
    if operator not in operations:
        raise ValueError(f"Unsupported non-null filter operator: {operator}")
    return operations[operator]()


def _execute_plan(plan, tables, query, route):
    """Validate and execute a query-driven plan; validate only declared relationships."""
    key = lambda value: "".join(ch for ch in str(value or "").casefold() if ch.isalnum())
    route = normalize_route(route)
    if normalize_route(plan.get("route")) != route:
        raise ValueError(f"CSVQA plan route does not match {route}")
    specs = plan.get("tables")
    if not isinstance(specs, list) or not specs:
        raise ValueError("CSVQA plan requires a non-empty tables list")
    ignored = plan.get("ignored_file_indices") or []
    if not isinstance(ignored, list) or any(isinstance(i, bool) or not isinstance(i, int) for i in ignored):
        raise ValueError("ignored_file_indices must be a list of integers")
    by_index = {table["file_index"]: table for table in tables}
    used = {spec.get("file_index") for spec in specs}
    if used & set(ignored) or (used | set(ignored)) != set(by_index):
        raise ValueError("Every input file must be used or explicitly ignored exactly once")

    payload_tables, payload_by_id, used_conditions, view_counts = [], {}, [], {}
    for spec in specs:
        file_index, role = spec.get("file_index"), str(spec.get("role") or "data").strip()
        if isinstance(file_index, bool) or not isinstance(file_index, int) or file_index not in by_index:
            raise ValueError(f"Invalid CSV file_index: {file_index!r}")
        occurrence = view_counts.get(file_index, 0)
        view_counts[file_index] = occurrence + 1
        table_id = f"file_{file_index}_view_{occurrence}"
        table, frame = by_index[file_index], by_index[file_index]["frame"]
        requested = spec.get("columns", "*")
        columns = list(frame.columns) if requested == "*" or requested == ["*"] else requested
        if not isinstance(columns, list) or not columns or len(columns) != len(set(columns)):
            raise ValueError(f"Table {table_id!r} requires unique columns or '*'")
        unknown = [column for column in columns if column not in frame.columns]
        if unknown:
            raise ValueError(f"Unknown columns for table {table_id!r}: {unknown}")
        filters = spec.get("filters") or {}
        if not isinstance(filters, dict):
            raise ValueError(f"Filters for table {table_id!r} must be an object")
        logic, conditions = str(filters.get("logic", "and")).casefold(), filters.get("conditions") or []
        if not isinstance(conditions, list):
            raise ValueError(f"Invalid filter logic for table {table_id!r}")
        # A common schema slip puts the sole condition's operator in ``logic``.
        # It is unambiguous for one condition; multi-condition plans remain strict.
        if logic not in {"and", "or"}:
            sole_operator = str(conditions[0].get("operator", "")).casefold() if len(conditions) == 1 and isinstance(conditions[0], dict) else ""
            if logic != sole_operator:
                raise ValueError(f"Invalid filter logic for table {table_id!r}")
            logic = "and"
            filters = {**filters, "logic": logic}
        combined = None
        for condition in conditions:
            if not isinstance(condition, dict):
                raise ValueError(f"Invalid filter for table {table_id!r}: {condition!r}")
            column, operator = condition.get("column"), condition.get("operator")
            dtype, evidence = condition.get("dtype", "string"), str(condition.get("evidence") or "")
            if column not in frame.columns or operator not in FILTER_OPERATORS or dtype not in FILTER_DTYPES:
                raise ValueError(f"Invalid filter for table {table_id!r}: {condition}")
            raw_values = condition.get("value", [])
            raw_values = raw_values if isinstance(raw_values, list) else [raw_values]
            value_supported = bool(raw_values) and all(key(value) in key(query) for value in raw_values)
            if not evidence.strip() or (key(evidence) not in key(query) and not value_supported):
                raise ValueError(f"Filter lacks query evidence: {condition}")
            mask = _apply_condition(frame[column], condition)
            combined = mask if combined is None else (combined & mask if logic == "and" else combined | mask)
            used_conditions.append(condition)
        selected = frame if combined is None else frame.loc[combined]
        if selected.empty:
            raise ValueError(f"CSVQA plan returned zero rows for table {table_id!r}")
        records = [
            {"source_row": int(index), "values": {column: str(row[column]) for column in columns}}
            for index, row in selected.iterrows()
        ]
        payload = {
            "table_id": table_id, "file_index": file_index, "file_name": table["path"].name,
            "role": role or "data", "columns": columns, "original_rows": len(frame),
            "returned_rows": len(records), "filters": filters, "records": records,
        }
        payload_tables.append(payload)
        payload_by_id[table_id] = payload

    profile = _build_profile(tables, query)
    required_values = {
        term for file_profile in profile for term, matches in file_profile["query_terms"].items()
        if matches["value_matches"] and not matches["column_matches"]
    }
    condition_text = json.dumps(used_conditions, ensure_ascii=False)
    missing_filters = sorted(term for term in required_values if key(term) not in key(condition_text))
    if missing_filters:
        raise ValueError(f"Plan omitted explicit query subset filters: {missing_filters}")
    required_columns = {
        column for file_profile in profile for matches in file_profile["query_terms"].values()
        for column in matches["column_matches"]
    }
    selected_columns = {column for table in payload_tables for column in table["columns"]}
    missing_columns = sorted(required_columns - selected_columns)
    if missing_columns:
        raise ValueError(f"Plan omitted columns named by the query: {missing_columns}")

    relationships = plan.get("relationships") or []
    if not isinstance(relationships, list):
        raise ValueError("relationships must be a list")
    validated_relationships, matrix_checks = [], []
    for relationship in relationships:
        if not isinstance(relationship, dict) or relationship.get("type") != "matrix":
            raise ValueError(f"Unsupported relationship: {relationship!r}")
        matrix_id = relationship.get("matrix_table_id")
        row_axis_spec, column_axis_spec = relationship.get("row_axis") or {}, relationship.get("column_axis") or {}
        row_axis_id, column_axis_id = row_axis_spec.get("table_id"), column_axis_spec.get("table_id")
        if any(table_id not in payload_by_id for table_id in (matrix_id, row_axis_id, column_axis_id)):
            raise ValueError(f"Relationship references an unknown table_id: {relationship}")
        matrix_table, row_axis, column_axis = (
            payload_by_id[matrix_id], payload_by_id[row_axis_id], payload_by_id[column_axis_id]
        )
        row_id_column = relationship.get("row_id_column")
        row_axis_column, column_axis_column = row_axis_spec.get("id_column"), column_axis_spec.get("id_column")
        for table, column in (
            (matrix_table, row_id_column), (row_axis, row_axis_column), (column_axis, column_axis_column)
        ):
            if column not in table["columns"]:
                raise ValueError(f"Matrix ID column {column!r} is not selected for {table['table_id']!r}")

        def axis_keys(values, axis_name):
            normalized = [key(value) for value in values]
            if any(not value for value in normalized) or len(set(normalized)) != len(normalized):
                raise ValueError(f"Matrix {axis_name} IDs must be non-empty and unique: {values}")
            return normalized

        row_ids = [record["values"][row_axis_column] for record in row_axis["records"]]
        column_ids = [record["values"][column_axis_column] for record in column_axis["records"]]
        matrix_row_ids = [record["values"][row_id_column] for record in matrix_table["records"]]
        matrix_columns = [column for column in matrix_table["columns"] if column != row_id_column]
        checks = {
            "matrix_table_id": matrix_id,
            "shape": [len(matrix_table["records"]), len(matrix_columns)],
            "expected_shape": [len(row_ids), len(column_ids)],
            "row_ids_aligned": axis_keys(matrix_row_ids, "matrix row") == axis_keys(row_ids, "row axis"),
            "column_ids_aligned": axis_keys(matrix_columns, "matrix column") == axis_keys(column_ids, "column axis"),
        }
        if checks["shape"] != checks["expected_shape"] or not checks["row_ids_aligned"] or not checks["column_ids_aligned"]:
            raise ValueError(f"Matrix validation failed: {checks}")
        validated_relationships.append(relationship)
        matrix_checks.append(checks)

    payload_tables.sort(key=lambda table: (table["file_index"], table["table_id"]))
    validation = {"status": "OK", "matrix_checks": matrix_checks}
    return {
        "route": route, "query": str(query or ""), "tables": payload_tables,
        "relationships": validated_relationships, "ignored_file_indices": sorted(ignored),
        "validation": validation,
    }

## 5. CSVQA tool

Planned mode supplies structured data to the model and falls back to the full data if the extraction plan is invalid. Legacy mode retrieves every CSV row through FAISS, restores source order, and asks the model to provide relevant evidence.

In [109]:
def load_csv_documents(dataset_address):
    """Build one legacy document per source row in deterministic source order."""
    documents, source_order = [], 0
    for table in _load_tables(dataset_address):
        for source_row, row in table["frame"].iterrows():
            values = {str(column): str(row[column]) for column in row.index}
            documents.append(Document(
                page_content=json.dumps({"source_row": int(source_row), "values": values}, ensure_ascii=False),
                metadata={"source": str(table["path"]), "source_order": source_order},
            ))
            source_order += 1
    return documents


def build_csvqa_components(
    dataset_address, system_prompt, tool_description, *, route, user_query="",
    result_sink=None,
):
    """Build the shared CSVQA tool in query-planned or legacy FAISS mode."""
    route = normalize_route(route)
    planned = CSVQA_MODE_BY_ROUTE[route] == "planned"
    llm = make_llm()

    state = result_sink if result_sink is not None else {}

    def rag_answer(tool_query):
        documents = load_csv_documents(dataset_address)
        embeddings = make_embeddings()
        retriever = FAISS.from_documents(documents, embeddings).as_retriever(
            search_kwargs={"k": len(documents)}
        )
        retrieved = retriever.invoke(tool_query)
        source_order = [document.metadata.get("source_order") for document in retrieved]
        if len(retrieved) != len(documents) or sorted(source_order) != list(range(len(documents))):
            raise RuntimeError(
                "Legacy CSVQA retrieval did not return every source row exactly once"
            )
        retrieved = sorted(retrieved, key=lambda doc: doc.metadata["source_order"])
        prompt = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            (
                "human",
                "Original user query (the only authority for subsets):\n{user_query}\n\n"
                "Agent retrieval request (must not narrow beyond the original query):\n{input}",
            ),
        ])
        result = create_stuff_documents_chain(llm, prompt).invoke({
            "input": tool_query, "user_query": user_query, "context": retrieved,
        })
        if isinstance(result, dict):
            metadata = result.get("response_metadata") or result.get("metadata") or {}
            finish_reason = str(
                result.get("finish_reason") or metadata.get("finish_reason") or ""
            ).casefold()
            if finish_reason in {"length", "max_tokens", "max_output_tokens"}:
                raise RuntimeError("Legacy CSVQA model output was truncated by the service")
            answer = result.get("answer", result.get("output", ""))
        else:
            answer = result
        if not str(answer or "").strip():
            raise RuntimeError("Legacy CSVQA model returned an empty result")
        return str(answer)

    def qa_wrapper(tool_query):
        plan, planner_outputs, errors, status, fallback_reason = None, [], [], "LEGACY_FAISS", None
        attempt_count = 0
        if planned:
            tables = _load_tables(dataset_address)
            attempt_count = 1
            raw_output = ""
            try:
                plan, raw_output = _ask_extraction_plan(
                    llm, route, user_query, tables, system_prompt
                )
                payload = _execute_plan(plan, tables, user_query, route)
                planner_outputs.append(raw_output)
                observation = json.dumps(payload, ensure_ascii=False, sort_keys=True)
                status = "PLANNED"
            except (KeyError, TypeError, ValueError) as exc:
                planner_outputs.append(getattr(exc, "planner_output", raw_output))
                errors.append(str(exc))
                payload_tables = []
                for table in tables:
                    frame, columns = table["frame"], list(table["frame"].columns)
                    payload_tables.append({
                        "table_id": f"file_{table['file_index']}_view_0",
                        "file_index": table["file_index"], "file_name": table["path"].name,
                        "role": f"file_{table['file_index']}", "columns": columns,
                        "original_rows": len(frame), "returned_rows": len(frame),
                        "filters": {"logic": "and", "conditions": []},
                        "records": [{"source_row": int(index), "values": {
                            column: str(row[column]) for column in columns
                        }} for index, row in frame.iterrows()],
                    })
                fallback_reason = errors[-1] if errors else "planner did not produce a valid plan"
                observation = json.dumps({
                    "route": route, "query": str(user_query or ""), "tables": payload_tables,
                    "relationships": [], "ignored_file_indices": [],
                    "validation": {
                        "status": "FALLBACK_FULL_DATA", "planner_errors": errors,
                        "fallback_reason": fallback_reason,
                    },
                }, ensure_ascii=False, sort_keys=True)
                status = "FALLBACK_FULL_DATA"
        else:
            observation = rag_answer(tool_query)
        trace = {
            "version": "GPT4.1-LO", "mode": "planned" if planned else "legacy",
            "status": status, "plan": plan, "planner_attempt_count": attempt_count,
            "planner_outputs": planner_outputs, "planner_errors": errors,
            "validation_errors": errors, "fallback_reason": fallback_reason,
            "payload_hash": hashlib.sha256(observation.encode("utf-8")).hexdigest(),
        }
        state.clear()
        state.update({"observation": observation, "trace": trace})
        return observation

    return llm, Tool(name="CSVQA", func=qa_wrapper, description=tool_description), state

## 6. Problem classification

Retrieve reference examples and classify the query. The classifier and its retriever are cached with lru_cache to avoid rebuilding indexes for each case.

In [110]:
@lru_cache(maxsize=1)
def _get_classifier_retriever():
    documents = CSVLoader(
        file_path=str(PROJECT_ROOT / "Large_Scale_Or_Files/RefData_Large_Scale.csv"),
        encoding="utf-8-sig",
        content_columns=["prompt", "New Problem Type"],
    ).load()
    if not documents:
        raise RuntimeError("RefData contains no classification examples")
    embeddings = make_embeddings()
    return FAISS.from_documents(documents, embeddings).as_retriever(
        search_kwargs={"k": 5}
    )


def fileqa_retrieve(query):
    """Retrieve five raw classification examples without an additional LLM call.
    
    Args:
        query: Natural-language optimization problem or retrieval query.
    
    Returns:
        A formatted string containing the ranked retrieved examples.
    """
    retrieved = _get_classifier_retriever().invoke(str(query))
    if len(retrieved) != 5:
        raise RuntimeError(f"FileQA expected five examples, retrieved {len(retrieved)}")

    return "\n\n".join(
        f"[Retrieved example {rank}]\n{document.page_content}"
        for rank, document in enumerate(retrieved, start=1)
    )


few_shot_example = """
Example 1 — Network Revenue Management

Question:
What is the problem type of the following optimization problem? Text: There
are three products with corresponding revenues and independent demand
streams. The company decides how many requests to fulfil over a finite sales
horizon to maximize total revenue from fixed initial inventories.
Replenishment is not allowed, and fulfilment decisions are non-negative
integers.

Thought: I need to identify the mathematical structure. I should call FileQA
once to retrieve structurally similar labeled reference problems.

Action: FileQA

Action Input: finite-horizon revenue maximization with independent demand streams, fixed initial inventories, no replenishment, and integer demand-fulfilment decisions

Observation: The retrieved RefData examples contain finite-inventory
demand-fulfilment problems labeled Network Revenue Management.

Thought: Fixed inventories are allocated to demand fulfilment over a sales
horizon to maximize revenue. This is the defining NRM structure.

Final Answer: NRM


Example 2 — Mixture rather than Resource Allocation

Question:
What is the problem type of the following optimization problem? Text: A
manufacturer determines integer production quantities and integer batch
counts on several workstations. Each batch consumes machine capacity.
Production creates a byproduct that must either be sold or disposed of, and
the corresponding quantities must satisfy balance constraints.

Thought: This problem contains resource capacities, but I must check whether
it is a clean single-stage resource-allocation model or contains additional
interacting mechanisms. I should call FileQA once.

Action: FileQA

Action Input: integer production and batch-count decisions across multiple workstations with capacity constraints and coupled byproduct sale-or-disposal balance

Observation: The retrieved examples include resource-allocation and
non-standard production-planning models. The latter contain batch decisions,
multiple production components, and coupled balance constraints.

Thought: Ordinary capacity constraints alone could indicate RA. However,
integer batch counts, multiple workstations, and byproduct balance materially
change the formulation. Therefore, the problem is Mixture rather than RA.

Final Answer: Mixture


Example 3 — Others rather than Mixture

Question:
What is the problem type of the following optimization problem? Text: A
company selects a subset of independent projects. Each project has a profit
and consumes part of one available budget. Each project is represented by a
binary variable, and there are no precedence, dependency, assignment, batch,
flow, or multi-stage constraints.

Thought: I need to determine whether this is a hybrid model or a coherent
standard optimization family outside the five canonical classes. I should
call FileQA once.

Action: FileQA

Action Input: independent binary project selection maximizing profit under one budget constraint with no logical dependencies or additional coupling

Observation: The retrieved examples contain standard binary knapsack and
project-selection problems categorized as outside the five canonical
classes.

Thought: This is a clean knapsack-style model without interacting structures
or non-standard coupling. It should be Others, not Mixture.

Final Answer: Others
"""


prefix = f"""
You are the classification agent in LEAN-LLM-OPT. Classify the current
optimization problem into exactly one of the following seven semantic
classes:

- NRM: Network Revenue Management
- RA: Resource Allocation
- TP: Transportation Problem
- FLP: Facility Location Problem
- AP: Assignment Problem
- Mixture
- Others

You must follow the ReAct workflow and call FileQA exactly once.

FileQA retrieves structurally similar labeled optimization problems from
RefData. For the Action Input, provide a concise but complete structural
description that preserves the objective, decision variables, major
constraints, and important coupling mechanisms.

Retrieved examples are supporting evidence, not automatic votes. The current
problem description and its mathematical structure are authoritative.

Classify according to:

- the objective;
- the meanings and domains of the decision variables;
- the principal constraint families;
- coupling between decisions;
- whether the formulation contains multiple stages or additional modeling
  mechanisms.

Do not classify according to company names, application narratives,
filenames, CSV files, or isolated keywords.

Class definitions:

1. Network Revenue Management (NRM)

A problem that allocates fixed inventories or capacities to known or
stochastic demand streams in order to maximize revenue. Typical defining
features include demand fulfilment, finite inventory, a sales horizon, and
no replenishment.

2. Resource Allocation (RA)

A clean, primarily single-stage allocation of limited resources among
activities or products, usually with ordinary capacity constraints and an
additive objective.

Capacity constraints or integer production quantities alone do not make a
problem Mixture.

Do not choose RA when additional mechanisms materially change the
formulation, such as:

- batch-size or lot-count decisions;
- multiple interacting production stages, workstations, or devices;
- byproduct sale, disposal, or material-balance decisions;
- blending or proportion constraints interacting with production;
- logical dependencies or conditional decisions;
- selection followed by assignment;
- equilibrium-style balance equations;
- vehicle-count and shipment-quantity coupling.

3. Transportation Problem (TP)

A clean source-to-destination flow problem with source supplies, destination
demands, route shipment quantities, and route transportation costs.

Do not choose TP when the transportation structure is materially coupled
with mechanisms such as integer truck dispatch, vehicle-capacity decisions,
fixed-charge decisions, multi-stage transshipment, production decisions, or
other non-standard constraint families. Such a problem may be Mixture.

4. Facility Location Problem (FLP)

A problem containing facility-opening or location decisions with fixed
opening costs, together with assignment or shipment decisions that link
clients or demand points to opened facilities.

5. Assignment Problem (AP)

A clean one-to-one or matching-style assignment of agents, workers,
machines, products, or other entities to tasks.

If the problem first selects a subset of entities and then assigns them, or
combines assignment with multiple stages, logical dependencies, production,
flow, or other interacting constraint families, choose Mixture instead.

6. Mixture

A hybrid or non-standard optimization model in which multiple structures or
modeling mechanisms interact materially.

Choose Mixture when either:

(a) a canonical TP, NRM, RA, FLP, or AP structure is combined with an
important additional mechanism; or

(b) a non-core optimization model contains non-standard interacting
constraint families that prevent it from being a clean textbook instance.

Strong Mixture signals include:

- batch-size, lot-size, or integer-trip decisions coupled with quantities;
- logical implications, precedence, dependencies, or conditional decisions;
- subset selection coupled with assignment;
- blending or proportion requirements coupled with production or capacity;
- byproduct production, sale, disposal, or balance;
- multiple interacting workstations, devices, or production stages;
- equilibrium or cross-variable balance equations;
- truck-count or vehicle-capacity decisions coupled with transportation flow;
- several distinct decision families whose interactions materially affect
  the formulation.

A problem does not need to belong to two named canonical classes to be
Mixture. One recognizable base structure plus a material non-standard
coupling mechanism is sufficient.

7. Others

A clean and coherent optimization family outside NRM, RA, TP, FLP, and AP,
without the hybrid or non-standard interacting structure required for
Mixture.

Typical examples include:

- a standard diet problem;
- a pure knapsack or independent project-selection problem;
- a standard traveling salesperson problem;
- a standard workforce or shift-covering problem;
- a standard parallel-machine scheduling problem;
- another well-known outside family with one dominant mathematical
  structure.

A textbook blending model may be Others only when it is a standalone model
with ordinary ingredient-balance and quality constraints. If blending or
proportion decisions interact with production stages, capacities, equipment,
batch decisions, or other constraint families, choose Mixture.

Decision procedure:

1. Identify the objective, decision variables, and main constraints.

2. Determine whether the problem is a clean instance of NRM, RA, TP, FLP,
   or AP.

3. Even if a canonical base structure is present, check for a material
   additional mechanism such as batching, logical dependencies,
   selection-assignment coupling, byproducts, blending-production coupling,
   multiple stages, equilibrium equations, or vehicle-count coupling.

4. If such an additional mechanism materially changes the formulation,
   choose Mixture.

5. If the problem is a clean, well-known outside family with one dominant
   structure and no material hybrid coupling, choose Others.

6. When TP, NRM, RA, FLP, or AP cannot be confidently confirmed:
   - choose Mixture if multiple structures or non-standard constraints
     interact materially;
   - otherwise choose Others.

When deciding between Mixture and Others, choose Mixture if two different decision families or constraint mechanisms interact materially. Choose Others only when one standard textbook archetype explains all important variables and constraints.

7. Retrieved labels are evidence, not rules. Do not use majority voting.
   When retrieval conflicts with the current mathematical formulation,
   prioritize the current formulation.

Important boundary rules:

- Multiple ordinary resource-capacity constraints alone are not sufficient
  for Mixture; a clean allocation model remains RA.
- Integer variables alone are not sufficient for Mixture.
- A canonical structure plus a material additional decision mechanism is
  sufficient for Mixture.
- Mixture and Others are separate semantic labels even if they currently
  share the same downstream workflow route.

Return exactly one of the following label tokens in the Final Answer:

NRM, RA, TP, FLP, AP, Mixture, Others

Do not include explanations, punctuation, or multiple candidate labels in
the Final Answer.

Examples of the required ReAct process:

{few_shot_example}
"""


suffix = """
Begin!

Question: {input}
{agent_scratchpad}
"""


@lru_cache(maxsize=1)
def _get_classification_agent():
    llm = make_llm()
    tool = Tool(
        name="FileQA",
        func=fileqa_retrieve,
        description=(
            "Return five structurally similar Ref-Data examples and their labels. "
            "Use the complete optimization problem text as input."
        ),
    )
    return initialize_agent(
        tools=[tool], llm=llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        agent_kwargs={"prefix": prefix, "suffix": suffix}, verbose=True,
        handle_parsing_errors=True, max_iterations=4, return_intermediate_steps=True,
    )


def normalize_problem_class(value):
    """Normalize a raw label to one of the seven benchmark classes.
    
    Args:
        value: Input value to normalize, parse, or inspect.
    
    Returns:
        The canonical class label.
    """
    candidate = str(value or "").strip()
    final = re.findall(r"(?:Final Answer|Answer|Label|Class)\s*:\s*([^\n]+)", candidate, re.I)
    if final:
        candidate = final[-1].strip()
    upper = re.sub(r"\s+", " ", candidate.strip("`*_ .,:;").upper())
    aliases = {
        "TP": "TP", "TRANSPORTATION": "TP", "TRANSPORTATION PROBLEM": "TP",
        "NRM": "NRM", "NETWORK REVENUE MANAGEMENT": "NRM",
        "NETWORK REVENUE MANAGEMENT PROBLEM": "NRM",
        "RA": "RA", "RESOURCE ALLOCATION": "RA", "RESOURCE ALLOCATION PROBLEM": "RA",
        "FLP": "FLP", "UFLP": "FLP", "FACILITY LOCATION": "FLP",
        "FACILITY LOCATION PROBLEM": "FLP",
        "UNCAPACITATED FACILITY LOCATION PROBLEM": "FLP",
        "UNCAPACITED FACILITY LOCATION PROBLEM": "FLP",
        "AP": "AP", "ASSIGNMENT": "AP", "ASSIGNMENT PROBLEM": "AP",
        "MIXTURE": "Mixture", "OTHERS": "Others",    }
    if upper in aliases:
        return aliases[upper]
    if upper.startswith("OTHERS") or upper.startswith("SALES-BASED LINEAR PROGRAMMING"):
        return "Others"
    matches = [
        label for label, pattern in [
            ("Mixture", r"\bMIXTURE\b"),
            ("NRM", r"\bNRM\b|NETWORK REVENUE MANAGEMENT"),
            ("RA", r"\bRA\b|RESOURCE ALLOCATION"),
            ("TP", r"\bTP\b|TRANSPORTATION"),
            ("FLP", r"\bFLP\b|\bUFLP\b|FACILITY LOCATION"),
            ("AP", r"\bAP\b|ASSIGNMENT"),
            ("Others", r"\bOTHERS"),
        ]
        if re.search(pattern, upper)
    ]
    if len(matches) == 1:
        return matches[0]
    raise ValueError(f"Cannot unambiguously normalize class: {value!r}")


def class_to_workflow_route(label):
    """Map a semantic class to an executable workflow route.
    
    Args:
        label: Semantic problem-class label.
    
    Returns:
        The route name; Mixture and Others both map to Others.
    """
    normalized = normalize_problem_class(label)
    return "Others" if normalized in {"Mixture", "Others"} else normalized


def invoke_classifier(query):
    """Run the ReAct classification agent and validate its tool-use contract.
    
    Args:
        query: Natural-language optimization problem or retrieval query.
    
    Returns:
        A dictionary containing the raw output, normalized label, FileQA call count, and trace.
    
    Raises:
        RuntimeError: If the classifier violates the one-FileQA-call contract or emits an invalid label.
    """
    response = _get_classification_agent().invoke(str(query))
    steps = response.get("intermediate_steps", []) if isinstance(response, dict) else []
    fileqa_calls = sum(
        getattr(step[0], "tool", None) == "FileQA"
        for step in steps if isinstance(step, tuple) and step
    )
    if fileqa_calls != 1:
        raise RuntimeError(f"Classifier must call FileQA exactly once; observed {fileqa_calls}")
    output = str(response.get("output", "") if isinstance(response, dict) else response).strip()
    return {
        "output": output,
        "normalized_label": normalize_problem_class(output),
        "fileqa_calls": fileqa_calls,
        "intermediate_steps": steps,
    }

## 7. Route retrieval and NRM formulation

Cache route-example retrievers and formulate network revenue management problems using planned CSV data.

In [111]:
def formulate_with_csvqa(query, dataset_address, route, system_prompt, tool_description, prefix, suffix):
    """Run the shared CSVQA agent with the route's prompt and fixed data mode."""
    llm, qa_tool, csvqa_result = build_csvqa_components(
        dataset_address, system_prompt, tool_description, route=route, user_query=query,
    )
    agent = initialize_agent(
        tools=[qa_tool], llm=llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        agent_kwargs={"prefix": prefix, "suffix": suffix}, verbose=True,
        handle_parsing_errors=True, return_intermediate_steps=True,
    )
    result = invoke_react_with_required_csvqa(agent, query, route)
    return {"formulation": result["output"], **csvqa_result}


@lru_cache(maxsize=None)
def get_route_retriever(file_path, k):
    path = Path(file_path).expanduser()
    path = path if path.is_absolute() else PROJECT_ROOT / path
    documents = CSVLoader(file_path=str(path), encoding="utf-8").load()
    return FAISS.from_documents(documents, make_embeddings()).as_retriever(search_kwargs={"k": k})


def retrieve_similar_texts(query, retriever):
    return [doc.page_content for doc in retriever.invoke(query)]


def get_NRM_response(query, dataset_address):
    retrieve='product'
    retriever = get_route_retriever("Large_Scale_Or_Files/RAG_Example_NRM2_MD.csv", 1)
    few_shot_examples = []

    similar_results = retrieve_similar_texts(query, retriever)

    for content in similar_results:
        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip()  
        split_at_address = split_at_formulation[1].split("Label:", 1)
        data_address = split_at_address[0].strip()

        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip()  
        Related = split_at_label[1].strip()
        information = read_csv_compat(data_address)
        information_head = information[:36]

        example_data_description = "\nHere is the product data:\n"
        for i, r in information_head.iterrows():
            example_data_description += f"Product {i + 1}: {r['Product Name']}, revenue w_{i + 1} = {r['Revenue']}, demand rate a_{i + 1} = {r['Demand']}, initial inventory c_{i + 1} = {r['Initial Inventory']}\n"


        label = label.replace("{", "{{").replace("}", "}}")
        few_shot_examples.append(fr"""

Question: Based on the following problem description and data, please formulate a complete mathematical model using real data from retrieval. {problem_description}

Thought: I need to formulate the objective function and constraints of the linear programming model based on the user's description and the provided data. I should retrieve the relevant information from the CSV file. Pay attention: 1. If the data to be retrieved is not specified, retrieve the whole dataset instead. 2. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. 3. The final expressions should not be simplified or abbreviated.

Action: CSVQA

Action Input: Retrieve all the {retrieve} data {Related} to formulate the mathematical model with no simplification or abbreviation. Retrieve the documents in order, row by row. Use the given context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, retrieve all the data instead. Only present final answer in details of row, instead of giving a sheet format.

Observation: {example_data_description}

Thought: Now that I have the necessary data, construct the objective function and constraints using the retrieved data as parameters of the formula. Ensure to include any additional detailed constraints present in the problem description. Always pay attention to the variable type. If not mentioned, use nonnegative integer. Do NOT include any explanations, notes, or extra text. Format the expressions strictly in markdown ONLY in this exact format: {label}. Following this example. The expressions should not be simplified or abbreviated. Besides, I need to use the $$ or $ to wrap the mathematical expressions instead of \[, \], \( or \). I also should avoid using align, align* and other latex environments. Besides, I should also avoid using \begin, \end, \text.

Final Answer: 
{label}
""")

    few_shot_examples = "\n\n".join(few_shot_examples)
    csvqa_system_prompt = CSVQA_PLANNED_PROMPTS["NRM"]
    csvqa_tool_description = CSVQA_TOOL_DESCRIPTIONS["NRM"]

    route_instruction = """Call CSVQA exactly once and return an ABSTRACT model. Define
index sets, parameters, variables, objective, and constraints symbolically. Include a short Data
Mapping that identifies every source by exact table_id and exact column name. Do not copy record
values or literal record counts."""
    prefix = f"""You are an assistant that formulates mathematical optimization models.

    The examples below illustrate model structure only; never copy their data.

    {few_shot_examples}

    {route_instruction}
    Use the user query as the authority for objective sense, variable domains, boundary semantics,
    and additional constraints. Do not invent missing data or silently omit returned data.
    """

    suffix = """

    Begin!

    User Description: {input}
    {agent_scratchpad}"""

    return formulate_with_csvqa(
        query, dataset_address, "NRM", csvqa_system_prompt, csvqa_tool_description, prefix, suffix,
    )

## 8. Resource allocation

Build the route-specific formulation using CSV evidence and retrieved examples.

In [112]:
def get_RA_response(query, dataset_address):
    retrieve="product"

    retriever = get_route_retriever("Large_Scale_Or_Files/RAG_Example_RA2_MD.csv", 3)
    few_shot_examples = []
    similar_results =  retrieve_similar_texts(query, retriever)
    for content in similar_results:

        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip() 

        split_at_address = split_at_formulation[1].split("Label:", 1)
        data_address = split_at_address[0].strip()

        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip()  
        Related = split_at_label[1].strip()

        datas=data_address.split()
        information = []

        for data in datas:
            information.append(read_csv_compat(data))
        example_data_description = "\nHere is the data:\n"
        for df_index, df in enumerate(information):
            if df_index == 0:
                example_data_description += f"\nDataFrame {df_index + 1} - Capacity\n"
            elif df_index == 1:
                example_data_description += f"\nDataFrame {df_index + 1} - Products\n"

            for _, r in df.iterrows():
                description = ""
                description += ", ".join([f"{col} = {r[col]}" for col in df.columns])
                example_data_description += description + "\n"
        label = label.replace("{", "{{").replace("}", "}}")
        few_shot_examples.append(fr"""
Question: Based on the following problem description and data, please formulate a complete mathematical model using real data from retrieval. {problem_description}

Thought: I need to formulate the objective function and constraints of the linear programming model based on the user's description and the provided data. I should retrieve the relevant information from the CSV file. Pay attention: 1. If the data to be retrieved is not specified, retrieve the whole dataset instead. 2. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. 3. The final expressions should not be simplified or abbreviated.

Action: CSVQA

Action Input: Retrieve all the {retrieve} data {Related} to formulate the mathematical model with no simplification or abbreviation. Retrieve the documents in order from top to bottom. Use the retrieved context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, retrieve all the data instead. Only present final answer in details of row, instead of giving a sheet format.

Observation: {example_data_description}

Thought: Now that I have the necessary data, I would construct the objective function and constraints using the retrieved data as parameters of the formula. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula according to the retrieved 'product id'. Do NOT include any explanations, notes, or extra text. Respond ONLY in this exact format: {label}. Following this example. The expressions should not be simplified or abbreviated. Besides, I need to use the $$ or $ to wrap the mathematical expressions instead of \[, \], \( or \). I also should avoid using align, align* and other latex environments. Besides, I should also avoid using \begin, \end, \text.

Final Answer: 
{label}
""")

    few_shot_examples = "\n\n".join(few_shot_examples)
    csvqa_system_prompt = CSVQA_LEGACY_SYSTEM_PROMPT
    csvqa_tool_description = CSVQA_LEGACY_TOOL_DESCRIPTION

    route_instruction = """You MUST call CSVQA exactly once before the Final Answer and use all returned rows.
Keep the supplied file order and original row order. Never sort or reset an index.
Use an explicit business ID column when present; never synthesize business IDs from row numbers.
Do not infer a file's semantic role only from its filename or position.
Align profits, resource consumption, and capacities through explicit column/ID keys.
Every resource-capacity dimension must receive a capacity constraint, and each
activity must appear in the objective and all applicable resource constraints.
Infer integer/binary/continuous domains from the user description and data.
An item count or number of units to order, produce, allocate, or develop is a nonnegative integer
unless the original query explicitly permits fractional quantities or describes divisible material.
The words scale, quantity or allocation alone do not establish continuous variables.
Distinguish a global activity decision from separate resource-by-activity allocations. When independent
warehouses, machines or other resources can each allocate to activities, use decisions indexed by
both resource and activity; do not constrain one identical global expression by every resource's limit.
Each resource-indexed capacity constraint must depend on that resource through its decisions or
consumption coefficients. For different resource dimensions consumed by one global activity, retain
global activity variables and the dimension-specific consumption coefficients instead.
Never invent a total capacity, default RHS, or omitted consumption coefficient.
Return a complete numerical formulation containing the retrieved identifiers and coefficients.
"""
    prefix = f"""You are an assistant that formulates mathematical optimization models.

    The examples below illustrate model structure only; never copy their data.

    {few_shot_examples}

    {route_instruction}
    Use the user query as the authority for objective sense, variable domains, boundary semantics,
    and additional constraints. Do not invent missing data or silently omit returned data.
    """

    suffix = """

    Begin!

    User Description: {input}
    {agent_scratchpad}"""

    return formulate_with_csvqa(
        query, dataset_address, "RA", csvqa_system_prompt, csvqa_tool_description, prefix, suffix,
    )

## 9. Transportation

Build the route-specific formulation using CSV evidence and retrieved examples.

In [113]:
def get_TP_response(query, dataset_address):
    retrieve="capacity data and products data, "
    retriever = get_route_retriever("Large_Scale_Or_Files/RAG_Example_TP2_MD.csv", 3)
    few_shot_examples = []
    similar_results = retrieve_similar_texts(query, retriever)
    for content in similar_results:
        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip()

        split_at_address = split_at_formulation[1].split("Label:", 1)
        data_address = split_at_address[0].strip()

        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip()  
        Related = split_at_label[1].strip()

        datas=data_address.split()
        information = []

        for data in datas:
            information.append(read_csv_compat(data))
        example_data_description = "\nHere is the data:\n"
        for df_index, df in enumerate(information):
            if df_index == 0:
                example_data_description += f"\nDataFrame {df_index + 1} - Customer Demand\n"
            elif df_index == 1:
                example_data_description += f"\nDataFrame {df_index + 1} - Supply Capacity\n"
            elif df_index == 2:
                example_data_description += f"\nDataFrame {df_index + 1} - Transportation Cost\n"

            for _, r in df.iterrows():
                description = ""
                description += ", ".join([f"{col} = {r[col]}" for col in df.columns])
                example_data_description += description + "\n"
            retrieve += ', '.join(df.columns)+', '
        label = label.replace("{", "{{").replace("}", "}}")
        few_shot_examples.append(fr"""
Question: Based on the following problem description and data, please formulate a complete mathematical model using real data from retrieval. {problem_description}

Thought: I need to formulate the objective function and constraints of the linear programming model based on the user's description and the provided data. I should retrieve the relevant information from the CSV file. Pay attention: 1. If the data to be retrieved is not specified, retrieve the whole dataset instead. 2. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. 3. The final expressions should not be simplified or abbreviated.

Action: CSVQA

Action Input: Retrieve all the {retrieve} data {Related} to formulate the mathematical model with no simplification or abbreviation. Retrieve the documents in order. Use the given context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, make sure that all the data is retrieved. Only present final answer in details of row, instead of giving a sheet format.

Observation: {example_data_description}

Thought: Now that I have the necessary data, I would construct the objective function and constraints using the retrieved data as parameters of the formula. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. Do NOT include any explanations, notes, or extra text. Respond ONLY in this exact format: {label}. Following this example. The expressions should not be simplified or abbreviated. Besides, I need to use the $$ or $ to wrap the mathematical expressions instead of \[, \], \( or \). I also should avoid using align, align* and other latex environments. Besides, I should also avoid using \begin, \end, \text.

Final Answer: 
{label}
""")
    few_shot_examples = "\n\n".join(few_shot_examples)
    csvqa_system_prompt = CSVQA_LEGACY_SYSTEM_PROMPT
    csvqa_tool_description = CSVQA_LEGACY_TOOL_DESCRIPTION

    route_instruction = """Call CSVQA at least once and return a complete numerical formulation. Retrieved
Information must contain every identifier and coefficient required by downstream code. Preserve
source order and do not invent, aggregate, or silently omit data."""
    prefix = f"""You are an assistant that formulates mathematical optimization models.

    The examples below illustrate model structure only; never copy their data.

    {few_shot_examples}

    {route_instruction}
    Use the user query as the authority for objective sense, variable domains, boundary semantics,
    and additional constraints. Do not invent missing data or silently omit returned data.
    """

    suffix = """

    Begin!

    User Description: {input}
    {agent_scratchpad}"""

    return formulate_with_csvqa(
        query, dataset_address, "TP", csvqa_system_prompt, csvqa_tool_description, prefix, suffix,
    )

## 10. Assignment

Build the route-specific formulation using CSV evidence and retrieved examples.

In [114]:
def get_AP_response(query,dataset_address):
    retrieve=''
    retriever = get_route_retriever("Large_Scale_Or_Files/RAG_Example_AP2_MD.csv", 1)
    few_shot_examples = []
    similar_results =  retrieve_similar_texts(query, retriever)
    for content in similar_results:
        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip() 

        split_at_address = split_at_formulation[1].split("Label:", 1)
        data_address = split_at_address[0].strip()

        file_addresses = data_address.strip().split('\n')
        example_data_description = " "
        for file_address in file_addresses:
            try:
                df = read_csv_compat(file_address) 
                matrix = df.iloc[:,1:].values
                example_data_description +="C=" + np.array_str(matrix)+ "."
            except Exception as e:
                print(f"Error reading file {file_address}: {e}")
        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip() 
        label = label.replace("{", "{{").replace("}", "}}")
        Related=''
        few_shot_examples.append(fr"""
Question: Based on the following problem description and data, please formulate a complete mathematical model using real data from retrieval. {problem_description}

Thought: I need to formulate the objective function and constraints of the linear programming model based on the user's description and the provided data. I should retrieve the relevant information from the CSV file. Pay attention: 1. If the data to be retrieved is not specified, retrieve the whole dataset instead. 2. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. 3. The final expressions should not be simplified or abbreviated.

Action: CSVQA

Action Input: Retrieve all the {retrieve} data {Related} to formulate the mathematical model with no simplification or abbreviation. Retrieve the documents in order. Use the given context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, make sure that all the data is retrieved. Only present final answer in details of row, instead of giving a sheet format.

Observation: {example_data_description}

Thought: Now that I have the necessary data, I would construct the objective function and constraints using the retrieved data as parameters of the formula. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula according to the retrieved 'product id'. Do NOT include any explanations, notes, or extra text. Respond ONLY in this exact format: {label}. Following this example. The expressions should not be simplified or abbreviated. Besides, I need to use the $$ or $ to wrap the mathematical expressions instead of \[, \], \( or \). I also should avoid using align, align* and other latex environments. Besides, I should also avoid using \begin, \end, \text.

Final Answer: 
{label}
""")
        
    few_shot_examples = "\n\n".join(few_shot_examples)
    csvqa_system_prompt = 'Retrieve the documents in order from top to bottom. Use the retrieved context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, retrieve all the data instead.Context: {context}'
    csvqa_tool_description = 'Use this tool to answer Querys based on the provided CSV data and retrieve product data similar to the input query.'

    prefix = f"""You are an assistant that generates a mathematical model based on the user's description and provided CSV data.

            Please refer to the following example and generate the answer in the same format:

            {few_shot_examples}

            Note: Please retrieve all neccessary information from the CSV file to generate the answer. When you generate the answer, please output required parameters in a whole text, including all vectors and matrices.

            When you need to retrieve information from the CSV file, use the provided tool.

            """

    suffix = """

            Begin!

            User Description: {input}
            {agent_scratchpad}"""

    return formulate_with_csvqa(
        query, dataset_address, "AP", csvqa_system_prompt, csvqa_tool_description, prefix, suffix,
    )

## 11. Facility location

Build the route-specific formulation using CSV evidence and retrieved examples.

In [115]:
def get_FLP_response(query,dataset_address):
    retrieve='supplier'
    retriever = get_route_retriever("Large_Scale_Or_Files/RAG_Example_FLP2_MD.csv", 1)
    few_shot_examples = []
    similar_results =  retrieve_similar_texts(query, retriever)
    for content in similar_results:
        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip() 

        split_at_address = split_at_formulation[1].split("Label:", 1)
        data_address = split_at_address[0].strip()

        file_addresses = data_address.strip().split('\n')
        example_data_description = " "
        for df_index, file_address in enumerate(file_addresses):
            try:
                df = read_csv_compat(file_address) 
                if 'demand' in df.columns:
                    result = df['demand'].values.tolist()
                    example_data_description += "d=" + str(result) + "\n"
                elif 'fixed_costs' in df.columns:
                    result = df['fixed_costs'].values.tolist()
                    example_data_description +="c=" + str(result) + "\n"
                elif df_index == 2:
                    matrix = df.iloc[:,1:].values
                    example_data_description +="A=" + np.array_str(matrix)+ "."
                else:
                    for _, row in df.iterrows():
                        example_data_description += ", ".join([f"{col} = {row[col]}" for col in df.columns])
            except Exception as e:
                raise RuntimeError(f"Error reading file {file_address}: {e}") from e
        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip() 
        label = label.replace("{", "{{").replace("}", "}}")
        Related=''

        few_shot_examples.append(fr"""
Question: Based on the following problem description and data, please formulate a complete mathematical model using real data from retrieval. {problem_description}

Thought: I need to formulate the objective function and constraints of the linear programming model based on the user's description and the provided data. I should retrieve the relevant information from the CSV file. Pay attention: 1. If the data to be retrieved is not specified, retrieve the whole dataset instead. 2. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. 3. The final expressions should not be simplified or abbreviated.

Action: CSVQA

Action Input: Retrieve all the {retrieve} data {Related} to formulate the mathematical model with no simplification or abbreviation. Retrieve the documents in order. Use the given context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, make sure that all the data is retrieved. Only present final answer in details of row, instead of giving a sheet format.

Observation: {example_data_description}

Thought: Now that I have the necessary data, I would construct the objective function and constraints using the retrieved data as parameters of the formula. I should pay attention if there is further detailed constraint in the problem description. If so, I should generate additional constraint formula. Do NOT include any explanations, notes, or extra text. Respond ONLY in this exact format: {label}. Following this example. The expressions should not be simplified or abbreviated. Besides, I need to use the $$ or $ to wrap the mathematical expressions instead of \[, \], \( or \). I also should avoid using align, align* and other latex environments. Besides, I should also avoid using \begin, \end, \text.

Final Answer: 
{label}
""")

    few_shot_examples = "\n\n".join(few_shot_examples)
    csvqa_system_prompt = ('Retrieve the documents in order. Use the given context to answer the question. If mention a certain kind of product, retrieve all the relavant product information detail judging by its product name. If not mention a certain kind of product, make sure that all the data is retrieved.Context: {context}' + ' Preserve every facility ID, customer ID, FixedCost, Capacity, Demand, and cost-matrix axis together with its source-row position. FixedCost and Capacity must use the same facility ID; the matrix row and column IDs must explicitly match facilities and customers, with its source orientation and shape retained. Model a two-dimensional shipment decision only. Use a stated capacity when present; an absent capacity is unresolved evidence, not zero. Do not transpose, truncate, pad, zero-fill, or infer an extra commodity/product axis.')
    csvqa_tool_description = 'Use this tool to answer Querys based on the provided CSV data and retrieve product data similar to the input query.'

    prefix = f"""You are an assistant that generates a mathematical model based on the user's description and provided CSV data.

            Please refer to the following example and generate the answer in the same format:

            {few_shot_examples}

            Note: Please retrieve all neccessary information from the CSV file to generate the answer. When you generate the answer, please output required parameters in a whole text, including all vectors and matrices.

            When you need to retrieve information from the CSV file, use the provided tool.

            """

    suffix = """
            Begin!

            User Description: {input}
            {agent_scratchpad}"""

    return formulate_with_csvqa(
        query, dataset_address, "FLP", csvqa_system_prompt, csvqa_tool_description, prefix, suffix,
    )

## 12. Other and mixed problems

CSV cases use full-file statistics and query-name evidence alongside the first 10 rows, then generate an Abstract Model Plan and code that reads complete files. Evidence does not select rows automatically. Query-only modeling keeps the original notebook workflow.

In [116]:
def escape_braces(text: str) -> str:
    return text.replace("{", "{{").replace("}", "}}")


@lru_cache(maxsize=1)
def get_others_store():
    documents = CSVLoader(file_path=str(PROJECT_ROOT / OTHERS_RAG_PATH), encoding="utf-8").load()
    embeddings = make_embeddings()
    return FAISS.from_documents(documents, embeddings)


def retrieve_examples(store, query: str, k: int = 1):
    return store.as_retriever(search_kwargs={"k": k}).invoke(query)


def build_few_shot_Other(store, user_query: str, k: int = 1, t='Model'):
    """Format retrieved model or code examples from the Others reference CSV."""
    examples = []
    
    # retrieve k most-similar reference examples
    for doc in retrieve_examples(store, user_query, k=k):
        txt = doc.page_content
        
        try:
            if "prompt:" not in txt:
                parts = re.split(r'(Data_address:|Label:|Label_Code:)', txt, flags=re.IGNORECASE)
                prompt_part = parts[0].replace("prompt:", "").strip()
                label_model = parts[4].strip()
                label_code = parts[6].strip()
                
            else:
                prompt_part = txt.split("Data_address:")[0].replace("prompt:", "").strip()
                label_model = txt.split("Label:")[1].split("Label_Code:")[0].strip()
                label_code = txt.split("Label_Code:")[1].split("Related:")[0].strip() # Assuming "Related:" is last

        except Exception as e:
            print(f"[build_few_shot_Other Error] Failed to parse example: {e}. Content: {txt[:50]}")
            continue

        if t == 'Model':
            label_part = label_model
            ex = (
                "<EXAMPLE>\n"
                f"Question: {prompt_part}\n"
                "Thought: I need to create an Abstract Model Plan based on the user's query and the CSV Schema (data structure)\n"
                "Final Answer:\n"
                f"{label_part}\n"
                "</EXAMPLE>"
            )
            examples.append(escape_braces(ex))
        else:
            label_part = label_code
            ex = (
                "<EXAMPLE>\n"
                f"Question: {prompt_part}\n"
                "Thought: I need to generate a single, complete, executable Gurobi Python code block.\n"
                "Final Answer:\n"
                f"{label_part}\n"
                "</EXAMPLE>"
            )
            examples.append(escape_braces(ex))

    return "\n\n".join(examples)


def csv_schema_preview(dataset_address, query=""):
    """Preview plus full-file evidence; matching never chooses or filters the model data."""
    normalize = lambda value: re.sub(r"\s+", " ", str(value)).strip().casefold()
    normalized_query = normalize(query)
    quoted = re.findall(r'"([^"\n]+)"|“([^”\n]+)”|‘([^’\n]+)’|(?<!\w)\x27([^\x27\n]+)\x27(?!\w)', query)
    names = {normalize(next(part for part in group if part)) for group in quoted}
    blocks = []
    for raw in normalize_data_address(dataset_address).splitlines():
        path = Path(raw).expanduser()
        path = path if path.is_absolute() else PROJECT_ROOT / path
        typed = read_csv_compat(path)
        frame = read_csv_compat(path, dtype=str, keep_default_na=False)
        stats, columns, terms = {}, {}, set(names)
        for column in frame:
            values = frame[column]
            normalized = values.map(normalize)
            columns[column] = normalized
            present = values[normalized.ne("")]
            numbers = pd.to_numeric(present, errors="coerce")
            stats[column] = {"missing": int(normalized.eq("").sum()), "unique_nonempty": int(present.nunique())}
            if len(present) and numbers.notna().all():
                stats[column]["numeric_range"] = [float(numbers.min()), float(numbers.max())]
            # Unquoted evidence must literally name a real column or complete nonnumeric value.
            candidates = [column] + present.unique().tolist()
            for value in candidates:
                term = normalize(value)
                if term and not re.fullmatch(r"[-+\d.,%]+", term) and re.search(r"(?<!\w)" + re.escape(term) + r"(?!\w)", normalized_query):
                    terms.add(term)
        evidence = []
        for term in sorted(terms):
            matches = []
            for column, values in columns.items():
                exact, prefix, contains = values.eq(term), values.str.startswith(term), values.str.contains(term, regex=False)
                if contains.any():
                    matches.append({"column": column, "exact": int(exact.sum()), "prefix": int(prefix.sum()),
                                    "contains": int(contains.sum()), "examples": frame.loc[contains, column].drop_duplicates().head(3).tolist()})
            evidence.append({"term": term, "matching_columns": matches,
                             "exact_matching_columns": sum(item["exact"] > 0 for item in matches)})
        blocks.append(
            f"File: {path.resolve()}\nCSV delimiter: comma; first line consumed as header.\nTotal rows: {len(frame)}\nColumns: {list(frame.columns)}\n"
            f"Parsed column types: {typed.dtypes.astype(str).to_dict()}\n"
            f"Preview only (first 10 rows):\n{frame.head(10).to_string(index=False)}\n"
            f"Full-file column statistics: {json.dumps(stats, ensure_ascii=False)}\n"
            "Matching uses casefold and collapsed/trimmed whitespace; original IDs and leading zeros are preserved.\n"
            "Counts are per column and per individual condition, not intersections. Empty matching_columns means zero matches in every column.\n"
            f"Query-name evidence: {json.dumps(evidence, ensure_ascii=False)}"
        )
    if not blocks:
        raise ValueError("No external CSV paths were supplied")
    return "\n\n---\n\n".join(blocks)


def get_Others_response(user_query: str, dataset_address: str):
    others_store = get_others_store()
    llm2 = make_llm()

    try:
        print("\n[Gurobi Pipeline Step 1/3]: Getting CSV Scheme...")

        schema = csv_schema_preview(dataset_address, query=user_query)        
        print("\n[Gurobi Pipeline Step 2/3]: Constructing Abstract Model...")

        few_shot_block_abstract = build_few_shot_Other(others_store, user_query, k=3, t='Model')
        print(f"[Few-Shot Abstract Examples]:\n{few_shot_block_abstract}...")
        
        abstract_model_template = """
You are an expert optimization modeler.
Your task is to create an "Abstract Model Plan" based on the user's query and the CSV Schema (data structure).
This plan is *not* Gurobi code or mathematical formulas, but a clear, step-by-step reasoning process in English.

[Examples]
{few_shot_examples}

[Current Task]
User Query: {query}

CSV Schema:
{schema}

An explicitly enumerated complete entity set in the query is authoritative: extra CSV entities
must not enlarge that set unless the query explicitly delegates its definition to the data.
For a one-off finite-horizon schedule, change/ramp constraints compare consecutive modeled periods. An initial
binary on/off state is not a pre-horizon continuous quantity: do not invent an initial continuous
level or a first-period ramp limit unless the query explicitly supplies that continuous boundary.
For recurring daily/cyclic operation, preserve wrap-around coverage across the last/first period
when a working shift spans the boundary; do not impose a fictitious empty start to a recurring day.
State and implement the original objective sense and complete value expression, including constants.
Do not offer sign-reversed or constant-shifted optimizer-equivalent objectives as alternatives.
Examples illustrate style; the current query and schema determine the actual scope, indices and boundaries.

Data selection: state for each entity table whether all rows or a subset is required; name the
filter column, exact condition, entity key, and joins. Preserve shared resource/parameter tables.
Without a query-requested filter, use the complete entity set. A preview is never the selected set.
Matching statistics are evidence, not instructions: do not broaden a zero-match condition to
substring matching or all rows. Check selected keys and applicable counts at runtime; recompute
combined conditions rather than treating individual counts as intersection counts.

[Your Output]
You must strictly follow this format for your "Abstract Model Plan" output:

[Abstract Model Plan START]
1.  **Analyze Query:** The user wants to {{{{Your analysis}}}}.
2.  **Identify Model Type:** Based on the query, this is a {{{{e.g., LP, MIP, Fixed-Charge, Blending}}}} problem.
3.  **Define Index Sets:** The primary indices are {{{{e.g., Products, Workers, Sources, Destinations}}}}.
4.  **Define Decision Variables:**
    -   `x[i]` = {{{{Describe first variable, e.g., 'quantity of product i'}}}}. Type: {{{{GRB.CONTINUOUS / GRB.INTEGER}}}}.
    -   `y[i]` = {{{{Describe second variable, e.g., 'if product i is produced'}}}}. Type: {{{{GRB.BINARY}}}}.
5.  **Identify Parameters (from Schema):**
    -   Objective coefficients (e.g., profit) will come from column(s): {{{{e.g., 'Price', 'Production Cost'}}}}.
    -   Constraint coefficients (e.g., resource use) will come from: {{{{e.g., 'Resource 1', 'Available Time'}}}}.
    -   Constraint RHS (limits) will come from: {{{{e.g., 'Max Demand'}}}}.
6.  **Formulate Objective:** {{{{Describe objective, e.g., 'Maximize sum((schema['Price'] - schema['Cost']) * x[i] - schema['FixedCost'] * y[i])'}}}}.
7.  **Formulate Constraints:**
    -   Constraint 1 (e.g., Resource Limit): {{{{Describe constraint 1, e.g., 'sum(schema['Resource 1'][i] * x[i]) <= schema['Available']'}}}}.
    -   Constraint 2 (e.g., Linking): {{{{Describe constraint 2, e.g., 'x[i] <= M * y[i])'}}}}.
    -   ... (Other constraints) ...
[Abstract Model Plan END]
"""
        abstract_prompt = PromptTemplate(
            template=abstract_model_template,
            input_variables=["query", "schema", "few_shot_examples"]
        )
        
        abstract_model_chain = LLMChain(llm=llm2, prompt=abstract_prompt)
        
        abstract_model_plan = abstract_model_chain.run(
            query=user_query,
            schema=schema,
            few_shot_examples=few_shot_block_abstract
        )
        print(f"[Observation]:\n{abstract_model_plan}")
        
        print("\n[Gurobi Pipeline Step 3/3]: Generating Gurobi Code...")
        
        few_shot_block_code = build_few_shot_Other(others_store, user_query, k=3, t='Code')
        
        code_gen_template = """
You are an expert Gurobi programmer.
Your task is to strictly follow the User Query, CSV Schema, and "Abstract Model Plan" to translate them into a single, complete, executable Gurobi Python code block.
The code must start with ```python and end with ```.
The code must include the necessary imports from gurobipy, pandas, numpy, re, math or json. Do not import sys or os.
Create exactly one Gurobi model in m or model and call its optimize() exactly once, both at top level. Do not wrap model creation or solving in functions or try/except; let errors propagate to the execution harness. Do not write files or call computeIIS().
The code must read all supplied CSV files needed by the model, at these exact newline-separated paths:
{dataset_address}
Read their complete contents at runtime. The schema preview is not the full dataset.
Preserve explicit business identifiers and matrix axes; do not invent filenames or columns.
Data-reading contract: these files were parsed with pandas.read_csv(path, sep=',').
The displayed preview is space-aligned for readability; it does not imply a whitespace delimiter.
pandas already consumes the CSV header. Select entity and parameter rows through identifier values
or validated predicates, never guessed iloc offsets or a guessed number of header rows.
Normalize identifier types explicitly on both sides of every lookup/join, including matrix row
indices versus column labels. Preserve the actual identifiers and derive dimensions from all rows.
Series.apply receives one cell value, not a row; use vectorized column predicates or DataFrame.apply
with axis=1 when a predicate needs a row. Every comprehension must use the indices it binds, not
stale variables from a preceding loop. Do not silently skip failed conversions or missing coefficients.
Use setObjective for the exact metric requested by the query, including all additive constants,
signs and units. An optimizer-equivalent objective is not an equivalent reported objective value;
do not drop constant terms and then merely restore them in printed output.
The code must *fully* implement all variables, objectives, and constraints from the "Abstract Model Plan".

[Examples of the Full Process]
{few_shot_examples}

[User Query]
{query}

[CSV Schema]
{schema}

[Abstract Model Plan]
{abstract_plan}

An explicitly enumerated complete entity set in the query is authoritative: extra CSV entities
must not enlarge that set unless the query explicitly delegates its definition to the data.
For a one-off finite-horizon schedule, change/ramp constraints compare consecutive modeled periods. An initial
binary on/off state is not a pre-horizon continuous quantity: do not invent an initial continuous
level or a first-period ramp limit unless the query explicitly supplies that continuous boundary.
For recurring daily/cyclic operation, preserve wrap-around coverage across the last/first period
when a working shift spans the boundary; do not impose a fictitious empty start to a recurring day.
State and implement the original objective sense and complete value expression, including constants.
Do not offer sign-reversed or constant-shifted optimizer-equivalent objectives as alternatives.
Examples illustrate style; the current query and schema determine the actual scope, indices and boundaries.

Data selection: state for each entity table whether all rows or a subset is required; name the
filter column, exact condition, entity key, and joins. Preserve shared resource/parameter tables.
Without a query-requested filter, use the complete entity set. A preview is never the selected set.
Matching statistics are evidence, not instructions: do not broaden a zero-match condition to
substring matching or all rows. Check selected keys and applicable counts at runtime; recompute
combined conditions rather than treating individual counts as intersection counts.

Reserve m and model for the Gurobi model; never reuse them as loop variables or other values.
Keep solver display names short and separate from business keys. With long keys, create variables
individually under short display names and store them in a dictionary keyed by the original IDs;
do not let addVars expand long business keys into solver names. Apply the same rule to constraint names.

[Your Gurobi Code]
"""

        code_gen_prompt = PromptTemplate(
            template=code_gen_template,
            input_variables=["query", "schema", "abstract_plan", "dataset_address", "few_shot_examples"]
        )
        
        code_gen_chain = LLMChain(llm=llm2, prompt=code_gen_prompt)
        
        final_code = code_gen_chain.run(
            query=user_query,
            schema=schema,
            abstract_plan=abstract_model_plan,
            dataset_address=dataset_address,
            few_shot_examples=few_shot_block_code 
        )
        
        if "```python" in final_code:
            code_block = final_code.split("```python", 1)[1]
            if "```" in code_block:
                code_block = code_block.split("```", 1)[0]
            final_answer = "```python\n" + code_block.strip() + "\n```"
        else:
            if not final_code.strip().startswith("import"):
                print(f"[Warning] Step 3 output was not a valid code block. Output: {final_code[:200]}...")
                final_answer = f"Error: Code generation failed. LLM returned non-code output:\n{final_code}"
            else:
                print("[Warning] Step 3 output missed ```python tag, adding it.")
                final_answer = "```python\n" + final_code.strip() + "\n```"
            
        print(f"[Final Answer]:\n{final_answer}")
        return {
            "formulation": abstract_model_plan, "code": final_answer, "observation": schema,
            "trace": {"status": "LEGACY_SCHEMA", "planner_attempt_count": 0,
                      "payload_hash": hashlib.sha256(schema.encode()).hexdigest()},
        }

    except Exception as e:
        print(f"[Gurobi Pipeline Error]: {e}")
        raise


def get_others_without_CSV_response(query):
    llm = make_llm()

    loader = CSVLoader(file_path=str(PROJECT_ROOT / "Large_Scale_Or_Files/RAG_Example_Others_Without_CSV.csv"), encoding="utf-8")
    documents = loader.load()

    embeddings = OpenAIEmbeddings(openai_api_key=user_api_key)
    vectors = FAISS.from_documents(documents, embeddings)

    retriever = vectors.as_retriever(search_kwargs={'k': 5})
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
    )

    qa_tool = Tool(
        name="ORLM_QA",
        func=qa_chain.invoke,
        description=(
            "Use this tool to answer Querys."
            "Provide the Query as input, and the tool will retrieve the relevant information from the file and use it to answer the Query."
        ),
    )

    few_shot_examples = []
    similar_results = retrieve_similar_texts(query, retriever)

    for content in similar_results:

        split_at_formulation = content.split("Data_address:", 1)
        problem_description = split_at_formulation[0].replace("prompt:", "").strip()
        split_at_address = split_at_formulation[1].split("Label:", 1)
        split_at_label = split_at_address[1].split("Related:", 1)
        label = split_at_label[0].strip() 

        label = label.replace("{", "{{").replace("}", "}}")
        example = (
            "<EXAMPLE>\n"
            f"Question: {problem_description}\n\n"
            "Thought: Read the question and 1) identify the goal (minimize time/cost/crew or maximize throughput/value) and collect per-unit coefficients; 2) define decision variables and pick domains: counts of trips/units/vehicles are nonnegative integers, yes or no choices are binary, divisible flows or weights are nonnegative reals; 3) write the linear objective from the coefficients; 4) add constraints in this order: demand or target (exactly, at least, at most), capacity or supply upper bounds, flow conservation or stage linking across nodes or arcs, and any share or ratio limits rewritten as linear inequalities using the given per-unit rates, plus any minimum or maximum usage; 5) add nonnegativity and the chosen integrality or binary domains; 6) output only the LP: objective first, then constraints line by line with brief labels if needed, then a final line stating the variable domains."
            "Final Answer:\n"
            f"{label}\n"
            "</EXAMPLE>"
        )

        example = example.replace("{", "{{").replace("}", "}}")
        few_shot_examples.append(example)

    prefix = (
    f"{few_shot_examples}\n\n"
    """ 
    Use the following triggers to identify problem structures and apply the corresponding mathematical formulations.
    (1) INTEGER trigger:
    Question: A factory can run two machine types. How many of each machine should be installed given budget and space limits? Maximize output.
    Final Answer: 
    $\\max\\; p_1 x_1 + p_2 x_2$
    $\\text{{s.t. }} a_1 x_1 + a_2 x_2 \\le B,\\; s_1 x_1 + s_2 x_2 \\le S$
    $x_1, x_2 \\in \\mathbb{{Z}}_+.$
    (2) MULTI-PERIOD FLOW trigger:
    Question: Multi-period production with inventory and backorders. Costs for production/holding/backorder. Initial and terminal conditions given.
    Final Answer:
    \textbf{{Indices: }} t\\in T=\\{{1,\\dots,n\\}}. \\
    \textbf{{Given: }} d_t,\\ I_0,\\ B_0,\\ \\dots \\
    \textbf{{Vars: }} x_t\\ge0,\\ I_t\\ge0,\\ B_t\\ge0. \\
    \\min \\sum_t (c x_t + h I_t + p B_t) \\
    \text{{s.t. }} I_t - B_t = I_{{t-1}} - B_{{t-1}} + x_t - d_t,\\ \forall t \\
    I_n \\ge I^{{\\min}},\\ B_n=0.
    (3) LOGIC+BINARY trigger:
    Question: Choose exactly one option from set P and at least K items from set V, with quantities and budget.
    Final Answer:
    \textbf{{Sets: }} i\\in P,\\ j\\in V. \\ \textbf{{Vars: }} q_i,q_j\\ge0;\\ y_i\\in\\{{0,1\\}}, z_j\\in\\{{0,1\\}}.\\
    \\max \\sum_j f_j q_j \\
    \text{{s.t. }} \\sum_i y_i = 1,\\ \\sum_j z_j \\ge K \\
    0\\le q_i \\le M_i y_i,\\ \forall i;\\ \\ 0\\le q_j \\le M_j z_j,\\ \forall j \\
    \text{{Budget: }} \\sum_i c_i q_i + \\sum_j c_j q_j \\le B.
    """
    "USER QUESTION:\n{input}\n\n"
    "TASK:\n"
    "- Produce a complete LaTeX optimization model using ONLY information in the question.\n"
    "- Use a fixed structure INSIDE LaTeX: Indices/Sets; Given Parameters (convert all tables to arrays); Decision Variables (with domains); Objective; Constraints; Domain lines.\n"
    "- For multi-period problems, you MUST include state-balance recurrences and initial/terminal conditions explicitly.\n"
    "- Avoid nonlinear forms when possible: rewrite ratios/logic using linear constraints + binaries (big-M) with clearly defined M.\n\n"
    "You should decide VARIABLE–TYPE first!\n (If not mentioned or ambiguous, integer by default!)"
    "### FIRST RESPONSE FORMAT (exactly 3 lines) ###\n"
    "Thought: <brief>\n"
    "Action: ORLM_QA\n"
    "Action Input: {input}\n\n"
    "Begin."
)

    suffix = (
    "\n### AFTER OBSERVATION ###\n"
    "Respond with exactly two lines:\n"
    "Thought: <variable types: integer/binary/continuous>\n"
    "Final Answer: <ONLY LaTeX model. Must include: (i) indices/sets, (ii) parameter definitions (tables->arrays), (iii) explicit domain lines for EVERY variable, (iv) initial/terminal conditions if any. No prose.>\n"
    "Do NOT output anything else."
)

    agent = initialize_agent(
        tools=[qa_tool],
        llm=llm,
        agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        agent_kwargs={
            "prefix": prefix,
            "suffix": suffix,
            "input_variables": ["input"]
        },
        verbose=True,
        handle_parsing_errors=True,  # Enable error handling
    )

    openai.api_request_timeout = 60  
    query = query.replace('{','{{').replace('}','}}')
    output = agent.run({"input": query})

    return output

## 13. Generate Python code

get_code preserves the original query-only workflow. get_csv_code uses structured NRM data or the numerical formulation from CSVQA. Others with CSV already generates code in section 12. All prompt examples are defined in this notebook.

In [117]:
ORIGINAL_CODE_PROMPT = """
    You are an expert in mathematical optimization and Python programming. Your task is to write Python code to solve the provided mathematical optimization model using the Gurobi library. The code should include the definition of the objective function, constraints, and decision variables. Please don't add additional explanations. Please don't include ```python and ```.Below is the provided mathematical optimization model:

    Mathematical Optimization Model:
    {output}
    """

QUERY_ONLY_CODE_EXAMPLES = {
    "NRM": """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\max \\quad \\sum_i A_i \\cdot x_i$
Constraints
1. Inventory Constraints:
$\\quad \\quad x_i \\leq I_i, \\quad \forall i$
2. Demand Constraints:
$x_i \\leq d_i, \\quad \forall i$
3. Startup Constraint:
$\\sum_i x_i \\geq s$
Retrieved Information
$\\small I = [7550, 6244]$
$\\small A = [149, 389]$
$\\small d = [15057, 12474]$
$\\small s = 100$

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

# Create the model
m = gp.Model("Product_Optimization")

# Decision variables for the number of units of each product
x_1 = m.addVar(vtype=GRB.INTEGER, name="x_1") # Number of units of product 1
x_2 = m.addVar(vtype=GRB.INTEGER, name="x_2") # Number of units of product 2

# Objective function: Maximize 149 x_1 + 389 x_2
m.setObjective(149 * x_1 + 389 * x_2, GRB.MAXIMIZE)

# Constraints
m.addConstr(x_1 <= 7550, name="inventory_constraint_1")
m.addConstr(x_2 <= 6244, name="inventory_constraint_2")
m.addConstr(x_1 <= 15057, name="demand_constraint_1")
m.addConstr(x_2 <= 12474, name="demand_constraint_2")

# Non-negativity constraints are implicitly handled by the integer constraints (x_1, x_2 >= 0)

# Solve the model
m.optimize()

        """,
    "FLP": """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\min \\quad \\sum_{i} \\sum_{j} A_{ij} \\cdot x_{ij} + \\sum_{i} c_i \\cdot y_i$

Constraints
1. Demand Constraint:
$\\quad \\quad \\sum_i x_{ij} = d_j, \\quad \forall j$
2. Capacity Constraint:
$\\quad \\quad \\sum_j x_{ij} \\leq M \\cdot y_i, \\quad \forall i$
3. Non-negativity:
$\\quad \\quad x_{ij} \\geq 0, \\quad \forall i,j$
4. Binary Requirement:
$\\quad \\quad y_i \\in \\{0,1\\}, \\quad \forall i$

Retrieved Information
$\\small d = [1083, 776, 16214, 553, 17106, 594, 732]$
$\\small c = [102.33, 94.92, 91.83, 98.71, 95.73, 99.96, 98.16]$
$\\small A = \begin{bmatrix}
1506.22 & 70.90 & 8.44 & 260.27 & 197.47 & 71.71 & 61.19 \\  
1732.65 & 1780.72 & 567.44 & 448.68 & 29.00 & 1484.91 & 963.92 \\  
115.66 & 100.76 & 64.68 & 1324.53 & 64.99 & 134.88 & 2102.83 \\  
1254.78 & 1115.63 & 52.31 & 1036.16 & 892.63 & 1464.04 & 1383.41 \\  
42.90 & 891.01 & 1013.94 & 1128.72 & 58.91 & 42.89 & 1570.31 \\  
0.70 & 139.46 & 70.03 & 79.15 & 1482.00 & 0.91 & 110.46 \\  
1732.30 & 1780.44 & 486.50 & 523.74 & 522.08 & 82.48 & 826.41
\\end{bmatrix}$
$\\small M = \\sum_j d_j = 1083 + 776 + 16214 + 553 + 17106 + 594 + 732 = 38058 $

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB
import numpy as np

# Data
d = np.array([1083, 776, 16214, 553, 17106, 594, 732])
c = np.array([102.33, 94.92, 91.83, 98.71, 95.73, 99.96, 98.16])
A = np.array([[1506.22, 70.90, 8.44, 260.27, 197.47, 71.71, 61.19],  
[1732.65, 1780.72, 567.44, 448.68, 29.00, 1484.91, 963.92],  
[115.66, 100.76, 64.68, 1324.53, 64.99, 134.88, 2102.83],  
[1254.78, 1115.63, 52.31, 1036.16, 892.63, 1464.04, 1383.41],  
[42.90, 891.01, 1013.94, 1128.72, 58.91, 42.89, 1570.31],  
[0.70, 139.46, 70.03, 79.15, 1482.00, 0.91, 110.46],  
[1732.30, 1780.44, 486.50, 523.74, 522.08, 82.48, 826.41]])

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(A.shape[0], A.shape[1], lb=0, name="x")
y = m.addVars(A.shape[0], vtype=GRB.BINARY, name="y")

# Objective function
m.setObjective(gp.quicksum(A[i, j]*x[i, j] for i in range(A.shape[0]) for j in range(A.shape[1])) + gp.quicksum(c[i]*y[i] for i in range(A.shape[0])), GRB.MINIMIZE)

# Constraints
for j in range(A.shape[1]):
    m.addConstr(gp.quicksum(x[i, j] for i in range(A.shape[0])) == d[j], name=f"demand_constraint_{j}")

M = 1000000  # large number
for i in range(A.shape[0]):
    m.addConstr(-M*y[i] + gp.quicksum(x[i, j] for j in range(A.shape[1])) <= 0, name=f"M_constraint_{i}")

# Solve the model
m.optimize()
        """,
    "AP": """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\min \\quad \\sum_{i=1}^3 \\sum_{j=1}^3 c_{ij} \\cdot x_{ij}$

Constraints
1. Row Assignment Constraint:
$\\quad \\quad \\sum_{j=1}^3 x_{ij} = 1, \\quad \forall i \\in \\{1,2,3\\}$
2. Column Assignment Constraint:
$\\quad \\quad \\sum_{i=1}^3 x_{ij} = 1, \\quad \forall j \\in \\{1,2,3\\}$
3. Binary Constraint:
$\\quad \\quad x_{ij} \\in \\{0,1\\}, \\quad \forall i,j$

Retrieved Information
$\\small c = \begin{bmatrix}
3000 & 3200 & 3100 \\
2800 & 3300 & 2900 \\
2900 & 3100 & 3000 
\\end{bmatrix}$

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB
import numpy as np

# Data
c = np.array([
    [3000, 3200, 3100],
    [2800, 3300, 2900],
    [2900, 3100, 3000]
])

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(c.shape[0], c.shape[1], vtype=GRB.BINARY, name="x")

# Objective function
m.setObjective(gp.quicksum(c[i, j]*x[i, j] for i in range(c.shape[0]) for j in range(c.shape[1])), GRB.MINIMIZE)

# Constraints
for i in range(c.shape[0]):
    m.addConstr(gp.quicksum(x[i, j] for j in range(c.shape[1])) == 1, name=f"row_constraint_{i}")

for j in range(c.shape[1]):
    m.addConstr(gp.quicksum(x[i, j] for i in range(c.shape[0])) == 1, name=f"col_constraint_{j}")

# Solve the model
m.optimize()
""",
    "TP": """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\min \\quad \\sum_i \\sum_j c_{ij} \\cdot x_{ij}$

Constraints
1. Demand Constraint:
$\\quad \\quad \\sum_i x_{ij} \\geq d_j, \\quad \forall j$
2. Capacity Constraint:
$\\quad \\quad \\sum_j x_{ij} \\leq s_i, \\quad \forall i$

Retrieved Information
$\\small d = [94, 39, 65, 435]$
$\\small s = [2531, 20, 210, 241]$
$\\small c = \begin{bmatrix}
883.91 & 0.04 & 0.03 & 44.45 \\
543.75 & 23.68 & 23.67 & 447.75 \\
537.34 & 23.76 & 498.95 & 440.60 \\
1791.49 & 68.21 & 1432.48 & 1527.76
\\end{bmatrix}$

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

# Create the model
m = gp.Model("Optimization")

# Decision variables
x_S1_C1 = m.addVar(vtype=GRB.INTEGER, name="x_S1_C1")
x_S1_C2 = m.addVar(vtype=GRB.INTEGER, name="x_S1_C2")
x_S1_C3 = m.addVar(vtype=GRB.INTEGER, name="x_S1_C3")
x_S1_C4 = m.addVar(vtype=GRB.INTEGER, name="x_S1_C4")
x_S2_C1 = m.addVar(vtype=GRB.INTEGER, name="x_S2_C1")
x_S2_C2 = m.addVar(vtype=GRB.INTEGER, name="x_S2_C2")
x_S2_C3 = m.addVar(vtype=GRB.INTEGER, name="x_S2_C3")
x_S2_C4 = m.addVar(vtype=GRB.INTEGER, name="x_S2_C4")
x_S3_C1 = m.addVar(vtype=GRB.INTEGER, name="x_S3_C1")
x_S3_C2 = m.addVar(vtype=GRB.INTEGER, name="x_S3_C2")
x_S3_C3 = m.addVar(vtype=GRB.INTEGER, name="x_S3_C3")
x_S3_C4 = m.addVar(vtype=GRB.INTEGER, name="x_S3_C4")
x_S4_C1 = m.addVar(vtype=GRB.INTEGER, name="x_S4_C1")
x_S4_C2 = m.addVar(vtype=GRB.INTEGER, name="x_S4_C2")
x_S4_C3 = m.addVar(vtype=GRB.INTEGER, name="x_S4_C3")
x_S4_C4 = m.addVar(vtype=GRB.INTEGER, name="x_S4_C4")

# Objective function
m.setObjective(883.91 * x_S2_C1 + 0.04 * x_S2_C2 + 0.03 * x_S2_C3 + 44.45 * x_S2_C4 + 543.75 * x_S1_C1 + 23.68 * x_S1_C2 + 23.67 * x_S1_C3 + 447.75 * x_S1_C4 + 537.34 * x_S3_C1 + 23.76 * x_S3_C2 + 498.95 * x_S3_C3 + 440.60 * x_S3_C4 + 1791.49 * x_S4_C1 + 68.21 * x_S4_C2 + 1432.48 * x_S4_C3 + 1527.76 * x_S4_C4, GRB.MINIMIZE)

# Constraints
m.addConstr(x_S1_C1 + x_S2_C1 + x_S3_C1 + x_S4_C1 >= 94, name="demand_constraint1")
m.addConstr(x_S1_C2 + x_S2_C2 + x_S3_C2 + x_S4_C2 >= 39, name="demand_constraint2")
m.addConstr(x_S1_C3 + x_S2_C3 + x_S3_C3 + x_S4_C3 >= 65, name="demand_constraint3")
m.addConstr(x_S1_C4 + x_S2_C4 + x_S3_C4 + x_S4_C4 >= 435, name="demand_constraint4")
m.addConstr(x_S1_C1 + x_S1_C2 + x_S1_C3 + x_S1_C4 <= 2531, name="capacity_constraint1")
m.addConstr(x_S2_C1 + x_S2_C2 + x_S2_C3 + x_S2_C4 <= 20, name="capacity_constraint2")
m.addConstr(x_S3_C1 + x_S3_C2 + x_S3_C3 + x_S3_C4 <= 210, name="capacity_constraint3")
m.addConstr(x_S4_C1 + x_S4_C2 + x_S4_C3 + x_S4_C4 <= 241, name="capacity_constraint4")

# Solve the model
m.optimize()
        """,
    "RA": """
For example, here is a simple instance for reference:

Always remember: If not specified. All the variables are non-negative interger.

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\max \\quad \\sum_i \\sum_j p_i \\cdot x_{ij}$

Constraints
1. Capacity Constraint:
$\\quad \\quad \\sum_i a_i \\cdot x_{ij} \\leq c_j, \\quad \forall j$
2. Non-negativity Constraint:
$\\quad \\quad x_{ij} \\geq 0, \\quad \forall i,j$

Retrieved Information
$\\small p = [321, 309, 767, 300, 763, 318, 871, 522, 300, 275, 858, 593, 126, 460, 685, 443, 700, 522, 940, 598]$
$\\small a = [495, 123, 165, 483, 472, 258, 425, 368, 105, 305, 482, 387, 469, 341, 318, 104, 377, 213, 56, 131]$
$\\small c = [4466]$

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(20, vtype=GRB.INTEGER, name="x")

# Objective function
m.setObjective(sum(x[i]*c[i] for i in range(20)), GRB.MAXIMIZE)

# Constraints
m.addConstr(sum(x[i]*w[i] for i in range(20)) <= 4466, name="capacity_constraint")

# Coefficients for the objective function
c = [321, 309, 767, 300, 763, 318, 871, 522, 300, 275, 858, 593, 126, 460, 685, 443, 700, 522, 940, 598]

# Coefficients for the capacity constraint
w = [495, 123, 165, 483, 472, 258, 425, 368, 105, 305, 482, 387, 469, 341, 318, 104, 377, 213, 56, 131]

# Solve the model
m.optimize()
```

-----
Here is another simple instance for reference:

Objective Function:
$\\quad \\quad \\max \\quad \\sum_i p_i \\cdot x_i$

Constraints
1. Capacity Constraint:
$\\quad \\quad \\sum_i a_i \\cdot x_i \\leq 180$
2. Dependency Constraint:
$\\quad \\quad x_1 \\leq x_3$
3. Non-negativity Constraint:
$\\quad \\quad x_i \\geq 0, \\quad \forall i$

Retrieved Information
$\\small p = [888, 134, 129, 370, 921, 765, 154, 837, 584, 365]$
$\\small a = [4, 2, 4, 3, 2, 1, 2, 1, 3, 3]$

The corresponding Python code for this instance is as follows:

import gurobipy as gp
from gurobipy import GRB

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(10, vtype=GRB.INTEGER, name="x")

# Objective function
p = [888, 134, 129, 370, 921, 765, 154, 837, 584, 365]
m.setObjective(sum(x[i]*p[i] for i in range(10)), GRB.MAXIMIZE)

# Constraints
a = [4, 2, 4, 3, 2, 1, 2, 1, 3, 3]
m.addConstr(sum(x[i]*a[i] for i in range(10)) <= 180, name="capacity_constraint")
m.addConstr(x[0] <= x[2], name="dependency_constraint")

# Solve the model
m.optimize()
        
        """,
    "Others": """
For example, here is a simple instance for reference:

Mathematical Optimization Model:
Maximize 5x_S + 8x_F
Subject to
    2x_S + 5x_F <= 200
    x_S <= 0.3(x_S + x_F)
    x_F >= 10
    x_S, x_F _ Z+

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

# Create the model
m = gp.Model("Worker_Optimization")

# Decision variables for the number of seasonal (x_S) and full-time (x_F) workers
x_S = m.addVar(vtype=GRB.INTEGER, lb=0, name="x_S")  # Number of seasonal workers
x_F = m.addVar(vtype=GRB.INTEGER, lb=0, name="x_F")  # Number of full-time workers

# Objective function: Maximize Z = 5x_S + 8x_F
m.setObjective(5 * x_S + 8 * x_F, GRB.MAXIMIZE)

# Constraints
m.addConstr(2 * x_S + 5 * x_F <= 200, name="resource_constraint")
m.addConstr(x_S <= 0.3 * (x_S + x_F), name="seasonal_ratio_constraint")
m.addConstr(x_F >= 10, name="full_time_minimum_constraint")

# Non-negativity constraints are implicitly handled by the integer constraints (x_S, x_F >= 0)

# Solve the model
m.optimize()
```
The another example is:

Mathematical Optimization Model:
Minimize 919x_11 + 556x_12 + 951x_13 + 21x_21 + 640x_22 + 409x_23 + 59x_31 + 786x_32 + 304x_33
Subject to
    x_11 + x_12 + x_13 = 1
    x_21 + x_22 + x_23 = 1
    x_31 + x_32 + x_33 = 1
    x_11 + x_21 + x_31 = 1
    x_12 + x_22 + x_32 = 1
    x_13 + x_23 + x_33 = 1
    x_11, x_12, x_13, x_21, x_22, x_23, x_31, x_32, x_33 ∈ {{0,1}}

The corresponding Python code for this instance is as follows:

```python

import gurobipy as gp
from gurobipy import GRB
import numpy as np

# Data
c = np.array([
    [919, 556, 951],
    [21, 640, 409],
    [59, 786, 304]
])

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(c.shape[0], c.shape[1], vtype=GRB.BINARY, name="x")

# Objective function
m.setObjective(gp.quicksum(c[i, j]*x[i, j] for i in range(c.shape[0]) for j in range(c.shape[1])), GRB.MINIMIZE)

# Constraints
for i in range(c.shape[0]):
    m.addConstr(gp.quicksum(x[i, j] for j in range(c.shape[1])) == 1, name=f"row_constraint_{i}")

for j in range(c.shape[1]):
    m.addConstr(gp.quicksum(x[i, j] for i in range(c.shape[0])) == 1, name=f"col_constraint_{j}")

# Solve the model
m.optimize() 
```


-----  Here is a Capacitated Facility Location (MIP) instance for reference:----- 

Mathematical Optimization Model:
\\[
\begin{{aligned}}
\\min\\;& 10000\\,y_1 + 15010\\,y_2 + 12000\\,y_3 \\
& + 5x_{{11}} + 7x_{{12}} + 3x_{{13}} + 4x_{{14}} \\
& + 6x_{{21}} + 4x_{{22}} + 5x_{{23}} + 3x_{{24}} \\
& + 2x_{{31}} + 6x_{{32}} + 7x_{{33}} + 4x_{{34}} \\
\text{s.t.}\\;& \\sum_{i=1}^{3} x_{ij} \\ge d_j && \forall j=1,\\dots,4 \\
& \\sum_{j=1}^{4} x_{ij} \\le s_i\\,y_i && \forall i=1,\\dots,3 \\
& d = \\{100, 150, 200, 120\\} \\
& s = \\{300, 400, 250\\} \\
& y_i \\in \\{0,1\\} && \forall i \\
& x_{ij} \\ge 0 && \forall i,j
\\end{{aligned}}
\\]

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

# Data
facilities = [1, 2, 3]
customers = [1, 2, 3, 4]

# Fixed costs
fixed_costs = {1: 10000, 2: 15010, 3: 12000}

# Capacities
capacities = {1: 300, 2: 400, 3: 250}

# Demands
demands = {1: 100, 2: 150, 3: 200, 4: 120}

# Variable costs
var_costs = {
    (1, 1): 5, (1, 2): 7, (1, 3): 3, (1, 4): 4,
    (2, 1): 6, (2, 2): 4, (2, 3): 5, (2, 4): 3,
    (3, 1): 2, (3, 2): 6, (3, 3): 7, (3, 4): 4,
}
arcs = var_costs.keys()

m = gp.Model("CFLP_Example")

# Variables
y = m.addVars(facilities, vtype=GRB.BINARY, name="y")
x = m.addVars(arcs, name="x") # default lb=0

# Objective
obj_fixed = y.prod(fixed_costs)
obj_variable = x.prod(var_costs)
m.setObjective(obj_fixed + obj_variable, GRB.MINIMIZE)

# Demand Constraints
for j in customers:
    m.addConstr(x.sum('*', j) >= demands[j], name=f"demand_{j}")

# Capacity Constraints
for i in facilities:
    m.addConstr(x.sum(i, '*') <= capacities[i] * y[i], name=f"capacity_{i}")
    
m.optimize()
```

----- Here is a Traveling Salesperson Problem (TSP) instance for reference: -----

Mathematical Optimization Model:
\\[
\begin{aligned}
\\min \\quad & 15x_{12}+25x_{13}+35x_{14}+18x_{21}+30x_{23}+40x_{24} \\
& + 28x_{31}+20x_{32}+38x_{34}+45x_{41}+50x_{42}+55x_{43} \\
\text{s.t.}\\quad & \\sum_{j
eq i} x_{ij}=1 && \forall i=1,\\dots,4 \\
& \\sum_{i
eq j} x_{ij}=1 && \forall j=1,\\dots,4 \\
& u_i - u_j + 4x_{ij} \\le 3 && \forall i,j \\in \\{1,\\dots,4\\}, i 
eq j \\
& 1 \\le u_i \\le 4 && \forall i=1,\\dots,4 \\
& x_{ij} \\in \\{0,1\\} && \forall i 
eq j \\
& u_i \\in \\mathbb{Z} && \forall i
\\end{aligned}
\\]

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

n = 4
nodes = range(1, n + 1)

costs = {
    (1, 2): 15, (1, 3): 25, (1, 4): 35,
    (2, 1): 18, (2, 3): 30, (2, 4): 40,
    (3, 1): 28, (3, 2): 20, (3, 4): 38,
    (4, 1): 45, (4, 2): 50, (4, 3): 55,
}
arcs = costs.keys()

m = gp.Model("TSP_Example")

# Variables
x = m.addVars(arcs, vtype=GRB.BINARY, name="x")
u = m.addVars(nodes, vtype=GRB.INTEGER, lb=1, ub=n, name="u")

# Objective
m.setObjective(x.prod(costs), GRB.MINIMIZE)

# Constraints
for i in nodes:
    m.addConstr(x.sum(i, '*') == 1, name=f"leave_{i}")

for j in nodes:
    m.addConstr(x.sum('*', j) == 1, name=f"enter_{j}")

# MTZ Subtour Elimination
for i, j in arcs:
    m.addConstr(u[i] - u[j] + n * x[i, j] <= n - 1, name=f"MTZ_{i}_{j}")

m.optimize()
```
----- Here is a Maximum Flow Problem (LP) instance for reference: -----

Mathematical Optimization Model:
\\[
\begin{aligned}
\\max\\;& F \\
\text{s.t. } 
& f_{01}+f_{02} = F && \text{(Source 0)} \\
& f_{12}+f_{13}+f_{14} = f_{01} && \text{(Node 1)} \\
& f_{23}+f_{24} = f_{02} + f_{12} && \text{(Node 2)} \\
& f_{34} = f_{13} + f_{23} && \text{(Node 3)} \\
& f_{14}+f_{24}+f_{34} = F && \text{(Sink 4)} \\
& f_{01} \\le 25, f_{02} \\le 35 \\
& f_{12} \\le 12, f_{13} \\le 18, f_{14} \\le 8 \\
& f_{23} \\le 12, f_{24} \\le 22 \\
& f_{34} \\le 30 \\
& f_{ij} \\ge 0, F \\ge 0
\\end{aligned}
\\]

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB

capacities = {
    (0, 1): 25, (0, 2): 35,
    (1, 2): 12, (1, 3): 18, (1, 4): 8,
    (2, 3): 12, (2, 4): 22,
    (3, 4): 30
}
arcs = capacities.keys()
nodes = [0, 1, 2, 3, 4]
source = 0
sink = 4

m = gp.Model("MaxFlow_Example")

# Variables
f = m.addVars(arcs, name="f") # default lb=0
F = m.addVar(name="F", lb=0)

# Objective
m.setObjective(F, GRB.MAXIMIZE)

# Capacity Constraints
m.addConstrs((f[i, j] <= capacities[i, j] for i, j in arcs), name="cap")

# Balance Constraints
# Source
m.addConstr(f.sum(source, '*') - f.sum('*', source) == F, name="source_balance")

# Sink
m.addConstr(f.sum('*', sink) - f.sum(sink, '*') == F, name="sink_balance")

# Transshipment nodes
for i in [1, 2, 3]:
    m.addConstr(f.sum('*', i) - f.sum(i, '*') == 0, name=f"balance_{i}")

m.optimize()
```
""",
}
QUERY_ONLY_CODE_ALIASES = {
    "Network Revenue Management": "NRM",
    "Network Revenue Management Problem": "NRM",
    "Facility Location Problem": "FLP",
    "Facility Location": "FLP",
    "Assignment Problem": "AP",
    "Assignment": "AP",
    "Transportation Problem": "TP",
    "Transportation": "TP",
    "Resource Allocation": "RA",
    "Resource Allocation Problem": "RA"
}

CSV_CODE_GUIDANCE = {
    'FLP': """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\min \\quad \\sum_{i} \\sum_{j} A_{ij} \\cdot x_{ij} + \\sum_{i} c_i \\cdot y_i$

Constraints
1. Demand Constraint:
$\\quad \\quad \\sum_i x_{ij} = d_j, \\quad \\forall j$
2. Capacity Constraint:
$\\quad \\quad \\sum_j x_{ij} \\leq M \\cdot y_i, \\quad \\forall i$
3. Non-negativity:
$\\quad \\quad x_{ij} \\geq 0, \\quad \\forall i,j$
4. Binary Requirement:
$\\quad \\quad y_i \\in \\{0,1\\}, \\quad \\forall i$

Retrieved Information
$\\small d = [1083, 776, 16214, 553, 17106, 594, 732]$
$\\small c = [102.33, 94.92, 91.83, 98.71, 95.73, 99.96, 98.16]$
$\\small A = \\begin{bmatrix}
1506.22 & 70.90 & 8.44 & 260.27 & 197.47 & 71.71 & 61.19 \\\\  
1732.65 & 1780.72 & 567.44 & 448.68 & 29.00 & 1484.91 & 963.92 \\\\  
115.66 & 100.76 & 64.68 & 1324.53 & 64.99 & 134.88 & 2102.83 \\\\  
1254.78 & 1115.63 & 52.31 & 1036.16 & 892.63 & 1464.04 & 1383.41 \\\\  
42.90 & 891.01 & 1013.94 & 1128.72 & 58.91 & 42.89 & 1570.31 \\\\  
0.70 & 139.46 & 70.03 & 79.15 & 1482.00 & 0.91 & 110.46 \\\\  
1732.30 & 1780.44 & 486.50 & 523.74 & 522.08 & 82.48 & 826.41
\\end{bmatrix}$
$\\small M = \\sum_j d_j = 1083 + 776 + 16214 + 553 + 17106 + 594 + 732 = 38058 $

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB
import numpy as np

# Data
d = np.array([1083, 776, 16214, 553, 17106, 594, 732])
c = np.array([102.33, 94.92, 91.83, 98.71, 95.73, 99.96, 98.16])
A = np.array([[1506.22, 70.90, 8.44, 260.27, 197.47, 71.71, 61.19],  
[1732.65, 1780.72, 567.44, 448.68, 29.00, 1484.91, 963.92],  
[115.66, 100.76, 64.68, 1324.53, 64.99, 134.88, 2102.83],  
[1254.78, 1115.63, 52.31, 1036.16, 892.63, 1464.04, 1383.41],  
[42.90, 891.01, 1013.94, 1128.72, 58.91, 42.89, 1570.31],  
[0.70, 139.46, 70.03, 79.15, 1482.00, 0.91, 110.46],  
[1732.30, 1780.44, 486.50, 523.74, 522.08, 82.48, 826.41]])

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(A.shape[0], A.shape[1], lb=0, name="x")
y = m.addVars(A.shape[0], vtype=GRB.BINARY, name="y")

# Objective function
m.setObjective(gp.quicksum(A[i, j]*x[i, j] for i in range(A.shape[0]) for j in range(A.shape[1])) + gp.quicksum(c[i]*y[i] for i in range(A.shape[0])), GRB.MINIMIZE)

# Constraints
for j in range(A.shape[1]):
    m.addConstr(gp.quicksum(x[i, j] for i in range(A.shape[0])) == d[j], name=f"demand_constraint_{j}")

M = 1000000  # large number
for i in range(A.shape[0]):
    m.addConstr(-M*y[i] + gp.quicksum(x[i, j] for j in range(A.shape[1])) <= 0, name=f"M_constraint_{i}")

# Solve the model
m.optimize()
        """,
    'AP': """
For example, here is a simple instance for reference:

Mathematical Optimization Model:

Objective Function:
$\\quad \\quad \\min \\quad \\sum_{i=1}^3 \\sum_{j=1}^3 c_{ij} \\cdot x_{ij}$

Constraints
1. Row Assignment Constraint:
$\\quad \\quad \\sum_{j=1}^3 x_{ij} = 1, \\quad \\forall i \\in \\{1,2,3\\}$
2. Column Assignment Constraint:
$\\quad \\quad \\sum_{i=1}^3 x_{ij} = 1, \\quad \\forall j \\in \\{1,2,3\\}$
3. Binary Constraint:
$\\quad \\quad x_{ij} \\in \\{0,1\\}, \\quad \\forall i,j$

Retrieved Information
$\\small c = \\begin{bmatrix}
3000 & 3200 & 3100 \\\\
2800 & 3300 & 2900 \\\\
2900 & 3100 & 3000 
\\end{bmatrix}$

The corresponding Python code for this instance is as follows:

```python
import gurobipy as gp
from gurobipy import GRB
import numpy as np

# Data
c = np.array([
    [3000, 3200, 3100],
    [2800, 3300, 2900],
    [2900, 3100, 3000]
])

# Create the model
m = gp.Model("Optimization_Model")

# Decision variables
x = m.addVars(c.shape[0], c.shape[1], vtype=GRB.BINARY, name="x")

# Objective function
m.setObjective(gp.quicksum(c[i, j]*x[i, j] for i in range(c.shape[0]) for j in range(c.shape[1])), GRB.MINIMIZE)

# Constraints
for i in range(c.shape[0]):
    m.addConstr(gp.quicksum(x[i, j] for j in range(c.shape[1])) == 1, name=f"row_constraint_{i}")

for j in range(c.shape[1]):
    m.addConstr(gp.quicksum(x[i, j] for i in range(c.shape[0])) == 1, name=f"col_constraint_{j}")

# Solve the model
m.optimize()
""",
    'TP': """
For TP legacy, use the identifiers, coefficients, and dimensions in the numerical formulation.
Preserve matrix axes and orientation. Never assume a square matrix or invent entity counts.
""",
    'RA': """
For RA legacy, the complete numerical formulation and original query provide the data contract.
Use the actual identifiers and coefficients from the formulation; no canonical CSVQA_DATA exists.
Represent item counts and discrete units as nonnegative integers unless the original query explicitly
allows fractional quantities or describes divisible material. Do not infer continuity from scale alone.
Keep independent resource-by-activity allocations distinct from global activities consuming multiple
resource dimensions. A separate resource allocation requires that resource in the variable index;
a global activity consuming multiple dimensions requires the correct dimension-specific coefficients.
Every capacity constraint must use the corresponding resource decisions or consumption coefficients.
Never apply the same global expression against every independent warehouse's capacity. Preserve every
supplied capacity and per-unit coefficient, explicit business identifier, and query-supported constraint.
""",
    
}


PLANNED_CODE_INSTRUCTIONS = """
Use the formulation for model structure and Data Mapping; use CSVQA_DATA for all data.
The complete payload below is provided at execution as CSVQA_DATA. Do not define or overwrite
it, copy its rows into literals, or read local files. Derive dimensions and identifiers from its records.
Select tables by the exact table_id in Data Mapping; roles may repeat. Read records from
CSVQA_DATA["tables"][i]["records"], and read each field through record["values"][column_name].
Preserve record order and mapped axes. Do not read CSVQA_DATA["plan"].
Without a continuous pre-horizon value, start change/ramp constraints at the second period;
an initial binary state does not supply a continuous period-zero value.
Parse structured CSV text with a regex and fail explicitly if any clause is unmatched.
"""

LEGACY_CODE_INSTRUCTIONS = """
Build a self-contained program using the concrete coefficients and identifiers in the
Mathematical Optimization Model / Retrieved Information. Define all required data in the code.
Do not use CSVQA_DATA, external variables, or external files. Return executable code only.
"""

CSV_SOLVER_INSTRUCTIONS = """
For |linear expression| <= bound, use expression <= bound and expression >= -bound;
do not pass a non-variable expression to addGenConstrAbs.
Leave the solved Gurobi model in m or model. If using a function, return the model and assign it to m.
Set MIPGap=1e-4 before optimize(). If Status == GRB.OPTIMAL, print ObjVal and each variable's
VarName and X. Otherwise print the solver status; do not report an incumbent as optimal.
"""


def get_code(output, selected_problem):
    """Generate code for a query-only problem using the original notebook prompts."""
    route = QUERY_ONLY_CODE_ALIASES.get(selected_problem, selected_problem)
    example = QUERY_ONLY_CODE_EXAMPLES.get(route, QUERY_ONLY_CODE_EXAMPLES["Others"])
    prompt = ORIGINAL_CODE_PROMPT.format(output=output) + example
    response = make_llm().invoke([HumanMessage(content=prompt)])
    print(response.content)
    return response.content


def get_csv_code(output, route, original_query, data_payload=""):
    """Generate code from CSV-derived data: structured NRM data or a numerical formulation."""
    prompt = ORIGINAL_CODE_PROMPT.format(output=output) + f"\nOriginal Query:\n{original_query}\n"
    if data_payload:
        prompt += PLANNED_CODE_INSTRUCTIONS + f"\nComplete CSVQA_DATA:\n{data_payload}\n"
    else:
        prompt += LEGACY_CODE_INSTRUCTIONS
    prompt += CSV_CODE_GUIDANCE.get(normalize_route(route), "") + CSV_SOLVER_INSTRUCTIONS
    response = make_llm().invoke([HumanMessage(content=prompt)])
    print(response.content)
    return response.content

## 14. Execute and assemble results

The pipeline classifies, formulates, generates code, and solves once. Query-only cases use the original Others modeling agent and the code example for the predicted class. execute_code returns the optimal objective and variable values from m or model; failures retain any model and code already generated.

In [118]:
def _source_candidate(code):
    source = str(code).strip()
    match = re.fullmatch(r"```(?:python|py)?\s*\n(.*?)\n```", source, re.DOTALL)
    return match.group(1) if match else source


def execute_code(code):
    namespace = {"__name__": "__main__"}
    exec(_source_candidate(code), namespace)
    model = namespace["m"] if "m" in namespace else namespace["model"]
    with model:
        if model.Status != gp.GRB.OPTIMAL:
            raise RuntimeError(f"No optimal solution; solver status: {model.Status}")
        objective = model.ObjVal
        solution = [(v.VarName, v.X) for v in model.getVars()]
        print("Optimal objective:", objective)
        print("Optimal solution:", solution)
        return objective, solution


ROUTE_FORMULATORS = {
    "NRM": get_NRM_response, "RA": get_RA_response, "TP": get_TP_response,
    "AP": get_AP_response, "FLP": get_FLP_response,
}


def invoke_formulation(route, query, dataset_address):
    if not dataset_address:
        return {"formulation": get_others_without_CSV_response(query), "trace": {"status": "NOT_APPLICABLE"}}
    return ROUTE_FORMULATORS.get(normalize_route(route), get_Others_response)(query, dataset_address)


def case_fields(case):
    reference = case.get("label_objective")
    address = normalize_data_address(case.get("dataset_address"))
    return {
        "problem_id": str(case["problem_id"]), "query": str(case["Query"]),
        "dataset_address": address, "input_kind": "external_csv" if address else "query_only",
        "true_label": case.get("true_label"), "true_route": case.get("true_route"),
        "label_objective": float(reference) if reference is not None and pd.notna(reference) else None,
    }


def execute_pipeline_case(case, *, forced_route=None):
    """Classify, formulate, generate code, and solve; retain progress if a step fails."""
    record = {**case_fields(case), "forced_route": forced_route,
              "experiment_mode": "forced" if forced_route else "automatic"}
    query, address = record["query"], record["dataset_address"]
    try:
        if forced_route is not None and not address:
            raise ValueError("Forced routes require CSV inputs")
        classification = invoke_classifier(query) if forced_route is None else {}
        label = classification.get("normalized_label")
        route = normalize_route(forced_route) if forced_route is not None else class_to_workflow_route(label)
        record.update(predicted_label=label, assigned_route=route if address else "Others")
        formulation = invoke_formulation(route, query, address)
        mode = CSVQA_MODE_BY_ROUTE[route] if address else None
        payload = formulation.get("observation", "") if mode == "planned" else ""
        record.update(generated_model=formulation["formulation"], csvqa_observation=formulation.get("observation", ""), csvqa_mode=mode,
                      csvqa_status=formulation.get("trace", {}).get("status"))
        code = formulation.get("code")
        if code is None:
            if address:
                code = get_csv_code(formulation["formulation"], route, query, data_payload=payload)
            else:
                code = get_code(formulation["formulation"], route)
        source = _source_candidate(code)
        if payload:
            # Include NRM data so the saved program can run on its own.
            data = json.loads(payload) if isinstance(payload, str) else payload
            source = f"CSVQA_DATA = {pprint.pformat(data, sort_dicts=False, width=120)}\n{source}"
        record["solve_code"] = source
        objective, solution = execute_code(record["solve_code"])
        record.update(final_objective=objective, final_solution=solution, final_ok=True,
                      record_status="completed", cache_source="computed")
        return record
    except Exception as exc:
        exc.pipeline_context = record
        raise

## 15. Test datasets and scoring

Query is required. Dataset_address, Problem Type, and the reference objective (Label-objective or Label) are optional. Missing CSV paths select query-only modeling; missing reference labels leave the corresponding accuracy blank.

In [119]:
def normalize_data_address(value):
    if value is None or (not isinstance(value, str) and pd.isna(value)):
        return ""
    return "\n".join(line.strip() for line in str(value).splitlines() if line.strip())


def resolve_dataset_address(value):
    return "\n".join(
        str((path if path.is_absolute() else PROJECT_ROOT / path).resolve())
        for path in (Path(line).expanduser() for line in normalize_data_address(value).splitlines())
    )


def parse_label_objective(value):
    text = str(value).replace(",", "").replace("$", "").strip()
    match = re.search(r"Optimal\s+objective\s*([-+\d.eE]+)", text, re.I)
    result = float(match.group(1) if match else text)
    if not math.isfinite(result):
        raise ValueError(f"Reference objective is not finite: {value!r}")
    return result


def prepare_cases(test):
    """Accept Large-scale-or, IndustryOR, or a DataFrame with at least Query."""
    frame = test.copy()
    if "Query" not in frame:
        raise ValueError("The test dataset must contain a Query column")
    if frame["Query"].isna().any() or frame["Query"].astype(str).str.strip().eq("").any():
        raise ValueError("Every test row must contain a non-empty Query")
    if "problem_id" not in frame:
        frame["problem_id"] = [f"OR-{index + 1:03d}" if isinstance(index, (int, np.integer)) else f"OR-{position:03d}"
                               for position, index in enumerate(frame.index, 1)]
    frame["problem_id"] = frame["problem_id"].astype(str)
    addresses = frame.get("dataset_address", frame.get("Dataset_address", pd.Series("", index=frame.index)))
    frame["dataset_address"] = addresses.map(resolve_dataset_address)
    labels = frame.get("true_label", frame.get("Problem Type", pd.Series(None, index=frame.index, dtype=object)))
    frame["true_label"] = labels.map(lambda value: normalize_problem_class(value) if pd.notna(value) and str(value).strip() else None)
    frame["true_route"] = frame["true_label"].map(lambda label: class_to_workflow_route(label) if label else None)
    objectives = frame.get("label_objective", frame.get("Label-objective", frame.get("Label", pd.Series(None, index=frame.index, dtype=object))))
    frame["label_objective"] = objectives.map(lambda value: parse_label_objective(value) if pd.notna(value) and str(value).strip() else None)
    return frame


def load_benchmark(path=BENCHMARK_PATH):
    return prepare_cases(read_csv_compat(path))


def objective_is_correct(actual, expected, *, rel_tol=1e-4, abs_tol=1e-4):
    try:
        actual, expected = float(actual), float(expected)
        return math.isfinite(actual) and math.isfinite(expected) and math.isclose(actual, expected, rel_tol=rel_tol, abs_tol=abs_tol)
    except (TypeError, ValueError, OverflowError):
        return False


def finalize_record(record, *, rel_tol=1e-4, abs_tol=1e-4):
    result = dict(record)
    result["classification_correct"] = (
        result.get("predicted_label") == result["true_label"]
        if result.get("true_label") and result.get("experiment_mode") == "automatic" else None
    )
    reference = result.get("label_objective")
    result["solution_correct"] = (
        bool(result.get("final_ok") and objective_is_correct(result.get("final_objective"), reference, rel_tol=rel_tol, abs_tol=abs_tol))
        if reference is not None and pd.notna(reference) else None
    )
    return result

## 16. Save and reuse results

Each experiment has a small results.csv for Excel and one folder per case containing model.md, solve.py, and solution.json. CSV data overviews are saved as data_overview.md. Variables are stored as name/value pairs so repeated solver display names remain distinct. Completed rows with matching code and data fingerprints can be reused.

In [120]:
def _write_text_atomic(path, text, encoding):
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding=encoding, dir=path.parent, prefix=f".{path.name}.",
            suffix=".tmp", delete=False,
        ) as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


CSV_VALUE_READERS = {
    **dict.fromkeys(("final_ok", "classification_correct", "solution_correct"), lambda value: value == "True"),
    **dict.fromkeys(("final_objective", "label_objective"), float),
}
_RESULT_LOCK = RLock()


def load_records(csv_path):
    path = Path(csv_path)
    if not path.exists():
        return []
    rows = pd.read_csv(path, dtype=str, keep_default_na=False, encoding="utf-8-sig").to_dict("records")
    return [{key: CSV_VALUE_READERS.get(key, str)(value) if value else None
             for key, value in row.items()} for row in rows]


def record_key(record):
    return (str(record["problem_id"]), record.get("query", ""),
            normalize_data_address(record.get("dataset_address")), record.get("forced_route") or "AUTO")


RECORD_ARTIFACT_FILES = {"generated_model": "model.md", "solve_code": "solve.py", "csvqa_observation": "data_overview.md"}


def materialize_record(csv_path, record):
    """Load a saved record's artifacts so save_record can copy them to another result folder."""
    root, row = Path(csv_path).parent, dict(record)
    for field in RECORD_ARTIFACT_FILES:
        relative = row.pop(field + "_path", None)
        artifact = root / relative if relative else None
        if artifact is None or not artifact.is_file():
            return None
        try:
            row[field] = artifact.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            return None
    relative = row.pop("solution_path", None)
    artifact = root / relative if relative else None
    if artifact is None or not artifact.is_file():
        return None
    try:
        solution = json.loads(artifact.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None
    if not isinstance(solution, dict) or "variables" not in solution:
        return None
    row["final_solution"] = solution["variables"]
    return row


def save_record(csv_path, record):
    """Save readable case files, then atomically update the small results CSV."""
    path = Path(csv_path)
    # Percent-encoding preserves distinct IDs without treating them as paths.
    folder = path.parent / (path.stem + "_cases") / (record.get("forced_route") or "AUTO") / quote(str(record["problem_id"]), safe="").replace(".", "%2E")
    folder.mkdir(parents=True, exist_ok=True)
    row = dict(record)
    with _RESULT_LOCK, path.with_suffix(".csv.lock").open("a+") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        for field, filename in RECORD_ARTIFACT_FILES.items():
            content = row.pop(field, None)
            if content is not None:
                _write_text_atomic(folder / filename, str(content), "utf-8")
                row[field + "_path"] = str((folder / filename).relative_to(path.parent))
        if "final_solution" in row:
            solution = {"status": "OPTIMAL" if row.get("final_ok") else "ERROR",
                        "objective": row.get("final_objective"), "variables": row.pop("final_solution"),
                        "error": row.get("execution_error")}
            _write_text_atomic(folder / "solution.json", json.dumps(solution, ensure_ascii=False, indent=2, allow_nan=False), "utf-8")
            row["solution_path"] = str((folder / "solution.json").relative_to(path.parent))
        records = [old for old in load_records(path) if record_key(old) != record_key(row)] + [row]
        _write_text_atomic(path, pd.DataFrame(records).to_csv(index=False), "utf-8-sig")
    return records


def _source_fingerprint():
    notebook = json.loads(NOTEBOOK_PATH.read_text(encoding="utf-8"))
    source = "\n".join("".join(cell["source"]) for cell in notebook["cells"]
                       if cell["cell_type"] == "code" and "experiment" not in cell.get("metadata", {}).get("tags", []))
    digest = hashlib.sha256(source.encode())
    for path in sorted((PROJECT_ROOT / "Large_Scale_Or_Files").rglob("*.csv")):
        digest.update(str(path.relative_to(PROJECT_ROOT)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def case_fingerprint(case, route=None, *, source_fingerprint=None):
    fields = {"source": source_fingerprint or _source_fingerprint(), "model": MODEL_SNAPSHOT,
              "embedding_model": EMBEDDING_MODEL, "modes": CSVQA_MODE_BY_ROUTE,
              "query": str(case["Query"]), "forced_route": route}
    digest = hashlib.sha256(json.dumps(fields, sort_keys=True).encode())
    for raw in normalize_data_address(case.get("dataset_address")).splitlines():
        path = Path(raw)
        digest.update(str(path).encode())
        digest.update(path.read_bytes() if path.is_file() else b"MISSING_FILE")
    return digest.hexdigest()


def error_record(case, exc, forced_route=None):
    return {
        **case_fields(case), "assigned_route": forced_route, "predicted_label": None,
        **getattr(exc, "pipeline_context", {}),
        "experiment_mode": "forced" if forced_route else "automatic", "forced_route": forced_route,
        "final_ok": False, "final_objective": None, "final_solution": None,
        "execution_error": f"{type(exc).__name__}: {exc}", "execution_error_type": type(exc).__name__,
        "record_status": "error", "cache_source": "computed",
    }

## 17. Shared test runner

run_test(test, output_csv=...) accepts a DataFrame or CSV path. It classifies automatic cases, detects CSV availability per row, and saves each result immediately. Pass routes=WORKFLOW_ROUTES to test every route. Every failure stays in the results; missing reference answers are not scored.

In [121]:
def run_test(test, *, output_csv=RESULTS_DIR / "results.csv", routes=None, reuse_auto_csv=None,
             reuse_completed=True, continue_on_error=True, rel_tol=1e-4, abs_tol=1e-4):
    """Resume saved results regardless of code fingerprint; reuse_completed=False reruns local results."""
    frame = load_benchmark(test) if isinstance(test, (str, Path)) else prepare_cases(test)
    selected_routes = [None] if routes is None else [normalize_route(route) for route in routes]
    if not selected_routes or len(selected_routes) != len(set(selected_routes)):
        raise ValueError("Provide a non-empty list of distinct routes")
    if routes is not None and frame["dataset_address"].eq("").any():
        raise ValueError("Forced-route tests require case CSV inputs; use routes=None for query-only tests")
    stored = load_records(output_csv) if reuse_completed else []
    cached = {record_key(record): record for record in stored}
    auto_cached = {record_key(record): record for record in load_records(reuse_auto_csv)} if reuse_auto_csv else {}
    source = _source_fingerprint()
    results = []
    total = len(frame) * len(selected_routes)
    for case in frame.to_dict("records"):
        for route in selected_routes:
            key = (case["problem_id"], str(case["Query"]), case["dataset_address"], route or "AUTO")
            fingerprint = case_fingerprint(case, route, source_fingerprint=source)
            automatic = auto_cached.get(key[:-1] + ("AUTO",))
            record = None
            if (route is not None and route == case.get("true_route")
                    and automatic and automatic.get("assigned_route") == route
                    and automatic.get("record_status") in {"completed", "error"}):
                record = materialize_record(reuse_auto_csv, automatic)
                if record is None and automatic.get("record_status") == "error":
                    record = {key: value for key, value in automatic.items() if not key.endswith("_path")}
                    record["final_solution"] = None
                if record is not None:
                    record.update(**case_fields(case), experiment_mode="forced", forced_route=route,
                                  cache_source="oracle_auto_reuse")
            previous = cached.get(key)
            if record is not None:
                pass
            elif previous and (previous.get("record_status") == "error"
                              or (previous.get("record_status") == "completed"
                                  and materialize_record(output_csv, previous) is not None)):
                record = {**previous, **case_fields(case),
                          "cache_source": previous.get("cache_source") if previous.get("cache_source") == "oracle_auto_reuse" else "csv"}
            else:
                try:
                    record = execute_pipeline_case(case, forced_route=route)
                except Exception as exc:
                    record = error_record(case, exc, route)
                    if not continue_on_error:
                        record = finalize_record(record, rel_tol=rel_tol, abs_tol=abs_tol)
                        record["cache_fingerprint"] = fingerprint
                        save_record(output_csv, record)
                        raise
            record = finalize_record(record, rel_tol=rel_tol, abs_tol=abs_tol)
            record["cache_fingerprint"] = record.get("cache_fingerprint") if record.get("cache_source") == "csv" else fingerprint
            save_record(output_csv, record)
            results.append(record)
            print(f"[{len(results)}/{total}] {case['problem_id']} / {route or 'AUTO'}: {record['record_status']} [{record.get('cache_source')}]")
    return results


def evaluation_summary(records):
    frame = pd.DataFrame(records)
    if frame.empty:
        return pd.DataFrame(columns=["metric", "correct", "total", "accuracy"])
    rows = []
    if frame["experiment_mode"].eq("forced").all():
        oracle = frame.loc[frame["forced_route"].eq(frame["true_route"])]
        for label, correct, total in (
                ("Oracle routing accuracy", int(oracle["solution_correct"].eq(True).sum()), frame["problem_id"].nunique()),
                ("Solved accuracy", int(frame["final_ok"].eq(True).sum()), len(frame))):
            rows.append({"metric": label, "correct": correct, "total": total,
                         "accuracy": correct / total if total else None})
        return pd.DataFrame(rows)
    for field, label in (("final_ok", "Solved"), ("classification_correct", "Classification"), ("solution_correct", "Objective match")):
        values = frame[field].dropna() if field in frame else pd.Series(dtype=bool)
        total, correct = len(values), int(values.eq(True).sum())
        rows.append({"metric": label, "correct": correct, "total": total,
                     "accuracy": correct / total if total else None})
    return pd.DataFrame(rows)


def classification_confusion(records):
    frame = pd.DataFrame(records)
    frame = frame.loc[frame["true_label"].notna() & frame["experiment_mode"].eq("automatic")]
    predicted = frame["predicted_label"].fillna("Unclassified")
    columns = CLASS_LABELS + (["Unclassified"] if predicted.eq("Unclassified").any() else [])
    return pd.crosstab(frame["true_label"], predicted).reindex(index=CLASS_LABELS, columns=columns, fill_value=0)


def accuracy_by_class(records):
    frame = pd.DataFrame(records)
    grouped = frame.groupby("true_label").agg(
        total=("problem_id", "size"), classification_correct=("classification_correct", "sum"),
        classification_scored=("classification_correct", "count"), solution_correct=("solution_correct", "sum"),
        solution_scored=("solution_correct", "count"))
    for metric in ("classification", "solution"):
        grouped[metric + "_accuracy"] = grouped[metric + "_correct"] / grouped[metric + "_scored"].replace(0, np.nan)
    return grouped.reindex(CLASS_LABELS).rename_axis("true_label")


def forced_route_matrix(records):
    frame = pd.DataFrame(records)
    grouped = frame.groupby(["true_route", "assigned_route"])["solution_correct"].agg(correct="sum", total="count")
    formatted = grouped.apply(lambda row: f"{int(row.correct)}/{int(row.total)} ({row.correct / row.total:.2%})" if row.total else "Not scored", axis=1)
    return formatted.unstack("assigned_route").reindex(index=WORKFLOW_ROUTES, columns=WORKFLOW_ROUTES)


def accuracy_by_route(records):
    grouped = pd.DataFrame(records).groupby("assigned_route")["solution_correct"].agg(correct="sum", total="count")
    grouped["accuracy"] = grouped["correct"] / grouped["total"].replace(0, np.nan)
    return grouped.reindex(WORKFLOW_ROUTES)


def report_results(records, output_dir):
    """Display and save the tables appropriate to the experiment."""
    tables = {"summary": evaluation_summary(records)}
    if records:
        if all(row.get("experiment_mode") == "automatic" for row in records):
            tables.update(classification_confusion=classification_confusion(records), accuracy_by_class=accuracy_by_class(records))
        else:
            tables.update(route_matrix=forced_route_matrix(records), accuracy_by_route=accuracy_by_route(records))
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, table in tables.items():
        print(name.replace("_", " ").title())
        shown = table.copy()
        for column in shown.columns:
            if str(column).endswith("accuracy"):
                shown[column] = shown[column].map(lambda value: f"{value:.2%}" if pd.notna(value) else "Not scored")
        display(shown)
        table.to_csv(output_dir / f"{name}.csv", index=table.index.name is not None, encoding="utf-8-sig")
    return tables

## 18. Test Large-scale-or: automatic (101 cases)

Enable this cell to classify and solve all 101 cases. Results include a classification confusion matrix and classification/solution accuracy grouped by the seven true labels. Failed attempts remain in the denominators; unavailable reference labels are not scored.

In [122]:
RUN_AUTOMATIC = True
if RUN_AUTOMATIC:
    automatic_results = run_test(BENCHMARK_PATH, output_csv=RESULTS_DIR / "automatic/results.csv")
    report_results(automatic_results, RESULTS_DIR / "automatic")

[1/101] OR-001 / AUTO: completed [csv]
[2/101] OR-002 / AUTO: completed [csv]
[3/101] OR-003 / AUTO: completed [csv]
[4/101] OR-004 / AUTO: completed [csv]
[5/101] OR-005 / AUTO: completed [csv]
[6/101] OR-006 / AUTO: completed [csv]
[7/101] OR-007 / AUTO: completed [csv]
[8/101] OR-008 / AUTO: completed [csv]
[9/101] OR-009 / AUTO: completed [csv]
[10/101] OR-010 / AUTO: completed [csv]
[11/101] OR-011 / AUTO: completed [csv]
[12/101] OR-012 / AUTO: completed [csv]
[13/101] OR-013 / AUTO: error [csv]
[14/101] OR-014 / AUTO: completed [csv]
[15/101] OR-015 / AUTO: completed [csv]
[16/101] OR-016 / AUTO: completed [csv]
[17/101] OR-017 / AUTO: completed [csv]
[18/101] OR-018 / AUTO: completed [csv]
[19/101] OR-019 / AUTO: completed [csv]
[20/101] OR-020 / AUTO: completed [csv]
[21/101] OR-021 / AUTO: completed [csv]
[22/101] OR-022 / AUTO: completed [csv]
[23/101] OR-023 / AUTO: completed [csv]
[24/101] OR-024 / AUTO: completed [csv]
[25/101] OR-025 / AUTO: completed [csv]
[26/101] OR-026 / AUTO: completed [csv]
[27/101] OR-027 / AUTO: completed [csv]
[28/101] OR-028 / AUTO: completed [csv]
[29/101] OR-029 / AUTO: completed [csv]
[30/101] OR-030 / AUTO: completed [csv]
[31/101] OR-031 / AUTO: completed [csv]
[32/101] OR-032 / AUTO: completed [csv]
[33/101] OR-033 / AUTO: completed [csv]
[34/101] OR-034 / AUTO: completed [csv]
[35/101] OR-035 / AUTO: completed [csv]
[36/101] OR-036 / AUTO: completed [csv]
[37/101] OR-037 / AUTO: completed [csv]
[38/101] OR-038 / AUTO: completed [csv]
[39/101] OR-039 / AUTO: completed [csv]
[40/101] OR-040 / AUTO: completed [csv]
[41/101] OR-041 / AUTO: completed [csv]
[42/101] OR-042 / AUTO: completed [csv]
[43/101] OR-043 / AUTO: completed [csv]
[44/101] OR-044 / AUTO: completed [csv]
[45/101] OR-045 / AUTO: completed [csv]
[46/101] OR-046 / AUTO: completed [csv]
[47/101] OR-047 / AUTO: completed [csv]
[48/101] OR-048 / AUTO: completed [csv]
[49/101] OR-049 / AUTO: completed [csv]
[50/101] OR-050 / AUTO: completed [csv]
[51/101] OR-051 / AUTO: completed [csv]
[52/101] OR-052 / AUTO: completed [csv]
[53/101] OR-053 / AUTO: completed [csv]
[54/101] OR-054 / AUTO: completed [csv]
[55/101] OR-055 / AUTO: completed [csv]
[56/101] OR-056 / AUTO: completed [csv]
[57/101] OR-057 / AUTO: completed [csv]
[58/101] OR-058 / AUTO: completed [csv]
[59/101] OR-059 / AUTO: completed [csv]
[60/101] OR-060 / AUTO: completed [csv]
[61/101] OR-061 / AUTO: completed [csv]
[62/101] OR-062 / AUTO: completed [csv]
[63/101] OR-063 / AUTO: completed [csv]
[64/101] OR-064 / AUTO: completed [csv]
[65/101] OR-065 / AUTO: completed [csv]
[66/101] OR-066 / AUTO: completed [csv]
[67/101] OR-067 / AUTO: completed [csv]
[68/101] OR-068 / AUTO: completed [csv]
[69/101] OR-069 / AUTO: completed [csv]
[70/101] OR-070 / AUTO: completed [csv]
[71/101] OR-071 / AUTO: completed [csv]
[72/101] OR-072 / AUTO: completed [csv]
[73/101] OR-073 / AUTO: completed [csv]
[74/101] OR-074 / AUTO: completed [csv]
[75/101] OR-075 / AUTO: completed [csv]
[76/101] OR-076 / AUTO: completed [csv]
[77/101] OR-077 / AUTO: completed [csv]
[78/101] OR-078 / AUTO: completed [csv]
[79/101] OR-079 / AUTO: completed [csv]
[80/101] OR-080 / AUTO: completed [csv]
[81/101] OR-081 / AUTO: completed [csv]
[82/101] OR-082 / AUTO: completed [csv]
[83/101] OR-083 / AUTO: error [csv]
[84/101] OR-084 / AUTO: completed [csv]
[85/101] OR-085 / AUTO: error [csv]
[86/101] OR-086 / AUTO: completed [csv]
[87/101] OR-087 / AUTO: completed [csv]
[88/101] OR-088 / AUTO: completed [csv]
[89/101] OR-089 / AUTO: completed [csv]
[90/101] OR-090 / AUTO: completed [csv]
[91/101] OR-091 / AUTO: completed [csv]
[92/101] OR-092 / AUTO: completed [csv]
[93/101] OR-093 / AUTO: completed [csv]
[94/101] OR-094 / AUTO: completed [csv]
[95/101] OR-095 / AUTO: completed [csv]
[96/101] OR-096 / AUTO: completed [csv]
[97/101] OR-097 / AUTO: error [csv]
[98/101] OR-098 / AUTO: completed [csv]
[99/101] OR-099 / AUTO: completed [csv]
[100/101] OR-100 / AUTO: completed [csv]
[101/101] OR-101 / AUTO: completed [csv]
Summary

            metric  correct  total accuracy
0           Solved       97    101   96.04%
1   Classification       92    101   91.09%
2  Objective match       92    101   91.09%

Classification Confusion

predicted_label  TP  NRM  RA  FLP  AP  Mixture  Others
true_label
TP                9    0   0    0   0        0       0
NRM               0   25   0    0   0        0       0
RA                0    0  22    0   0        0       0
FLP               0    0   0   14   0        0       0
AP                0    0   0    0   5        0       0
Mixture           0    0   3    0   0       10       5
Others            0    0   1    0   0        0       7

Accuracy By Class

,total,classification_correct,classification_scored,solution_correct,solution_scored,classification_accuracy,solution_accuracy
true_label,,,,,,,
TP,9,9,9,8,9,100.00%,88.89%
NRM,25,25,25,23,25,100.00%,92.00%
RA,22,22,22,21,22,100.00%,95.45%
FLP,14,14,14,14,14,100.00%,100.00%
AP,5,5,5,5,5,100.00%,100.00%
Mixture,18,10,18,15,18,55.56%,83.33%
Others,8,7,8,6,8,87.50%,75.00%

## 19. Test Large-scale-or: all routes (606 cases)

Enable this cell to run every problem through all six routes. For the oracle route, a complete AUTO result is copied into the forced result folder when AUTO selected that same route; otherwise that route is executed normally. True Others and Mixture both map to Others. Each cell shows correct/total (accuracy); the route summary reports each route across all 101 cases.

In [123]:
RUN_FORCED_ROUTES = True
if RUN_FORCED_ROUTES:
    forced_route_results = run_test(BENCHMARK_PATH, output_csv=RESULTS_DIR / "forced/results.csv", routes=WORKFLOW_ROUTES,
                                    reuse_auto_csv=RESULTS_DIR / "automatic/results.csv")
    report_results(forced_route_results, RESULTS_DIR / "forced")

[1/606] OR-001 / TP: completed [oracle_auto_reuse]
[2/606] OR-001 / NRM: completed [csv]
[3/606] OR-001 / FLP: completed [csv]
[4/606] OR-001 / AP: completed [csv]
[5/606] OR-001 / RA: completed [csv]
[6/606] OR-001 / Others: completed [csv]
[7/606] OR-002 / TP: completed [oracle_auto_reuse]
[8/606] OR-002 / NRM: completed [csv]
[9/606] OR-002 / FLP: completed [csv]
[10/606] OR-002 / AP: completed [csv]
[11/606] OR-002 / RA: completed [csv]
[12/606] OR-002 / Others: completed [csv]
[13/606] OR-003 / TP: completed [oracle_auto_reuse]
[14/606] OR-003 / NRM: completed [csv]
[15/606] OR-003 / FLP: completed [csv]
[16/606] OR-003 / AP: completed [csv]
[17/606] OR-003 / RA: completed [csv]
[18/606] OR-003 / Others: completed [csv]
[19/606] OR-004 / TP: completed [oracle_auto_reuse]
[20/606] OR-004 / NRM: completed [csv]
[21/606] OR-004 / FLP: completed [csv]
[22/606] OR-004 / AP: completed [csv]
[23/606] OR-004 / RA: completed [csv]
[24/606] OR-004 / Others: completed [csv]
[25/606] OR-005 / TP: completed [oracle_auto_reuse]
[26/606] OR-005 / NRM: completed [csv]
[27/606] OR-005 / FLP: completed [csv]
[28/606] OR-005 / AP: completed [csv]
[29/606] OR-005 / RA: completed [csv]
[30/606] OR-005 / Others: completed [csv]
[31/606] OR-006 / TP: completed [oracle_auto_reuse]
[32/606] OR-006 / NRM: completed [csv]
[33/606] OR-006 / FLP: completed [csv]
[34/606] OR-006 / AP: completed [csv]
[35/606] OR-006 / RA: completed [csv]
[36/606] OR-006 / Others: completed [csv]
[37/606] OR-007 / TP: completed [oracle_auto_reuse]
[38/606] OR-007 / NRM: completed [csv]
[39/606] OR-007 / FLP: completed [csv]
[40/606] OR-007 / AP: completed [csv]
[41/606] OR-007 / RA: completed [csv]
[42/606] OR-007 / Others: completed [csv]
[43/606] OR-008 / TP: completed [oracle_auto_reuse]
[44/606] OR-008 / NRM: completed [csv]
[45/606] OR-008 / FLP: completed [csv]
[46/606] OR-008 / AP: completed [csv]
[47/606] OR-008 / RA: completed [csv]
[48/606] OR-008 / Others: completed [csv]
[49/606] OR-009 / TP: completed [oracle_auto_reuse]
[50/606] OR-009 / NRM: completed [csv]
[51/606] OR-009 / FLP: completed [csv]
[52/606] OR-009 / AP: completed [csv]
[53/606] OR-009 / RA: completed [csv]
[54/606] OR-009 / Others: completed [csv]
[55/606] OR-010 / TP: completed [csv]
[56/606] OR-010 / NRM: completed [oracle_auto_reuse]
[57/606] OR-010 / FLP: completed [csv]
[58/606] OR-010 / AP: completed [csv]
[59/606] OR-010 / RA: completed [csv]
[60/606] OR-010 / Others: completed [csv]
[61/606] OR-011 / TP: completed [csv]
[62/606] OR-011 / NRM: completed [oracle_auto_reuse]
[63/606] OR-011 / FLP: completed [csv]
[64/606] OR-011 / AP: completed [csv]
[65/606] OR-011 / RA: completed [csv]
[66/606] OR-011 / Others: completed [csv]
[67/606] OR-012 / TP: error [csv]
[68/606] OR-012 / NRM: completed [oracle_auto_reuse]
[69/606] OR-012 / FLP: error [csv]
[70/606] OR-012 / AP: error [csv]
[71/606] OR-012 / RA: error [csv]
[72/606] OR-012 / Others: completed [csv]
[73/606] OR-013 / TP: error [csv]
[74/606] OR-013 / NRM: error [oracle_auto_reuse]
[75/606] OR-013 / FLP: error [csv]
[76/606] OR-013 / AP: error [csv]
[77/606] OR-013 / RA: error [csv]
[78/606] OR-013 / Others: completed [csv]
[79/606] OR-014 / TP: error [csv]
[80/606] OR-014 / NRM: completed [oracle_auto_reuse]
[81/606] OR-014 / FLP: error [csv]
[82/606] OR-014 / AP: completed [csv]
[83/606] OR-014 / RA: completed [csv]
[84/606] OR-014 / Others: completed [csv]
[85/606] OR-015 / TP: completed [csv]
[86/606] OR-015 / NRM: completed [oracle_auto_reuse]
[87/606] OR-015 / FLP: completed [csv]
[88/606] OR-015 / AP: completed [csv]
[89/606] OR-015 / RA: completed [csv]
[90/606] OR-015 / Others: completed [csv]
[91/606] OR-016 / TP: completed [csv]
[92/606] OR-016 / NRM: completed [oracle_auto_reuse]
[93/606] OR-016 / FLP: completed [csv]
[94/606] OR-016 / AP: error [csv]
[95/606] OR-016 / RA: completed [csv]
[96/606] OR-016 / Others: completed [csv]
[97/606] OR-017 / TP: completed [csv]
[98/606] OR-017 / NRM: completed [oracle_auto_reuse]
[99/606] OR-017 / FLP: completed [csv]
[100/606] OR-017 / AP: completed [csv]
[101/606] OR-017 / RA: completed [csv]
[102/606] OR-017 / Others: completed [csv]
[103/606] OR-018 / TP: completed [csv]
[104/606] OR-018 / NRM: completed [oracle_auto_reuse]
[105/606] OR-018 / FLP: completed [csv]
[106/606] OR-018 / AP: completed [csv]
[107/606] OR-018 / RA: completed [csv]
[108/606] OR-018 / Others: completed [csv]
[109/606] OR-019 / TP: completed [csv]
[110/606] OR-019 / NRM: completed [oracle_auto_reuse]
[111/606] OR-019 / FLP: completed [csv]
[112/606] OR-019 / AP: completed [csv]
[113/606] OR-019 / RA: completed [csv]
[114/606] OR-019 / Others: completed [csv]
[115/606] OR-020 / TP: completed [csv]
[116/606] OR-020 / NRM: completed [oracle_auto_reuse]
[117/606] OR-020 / FLP: completed [csv]
[118/606] OR-020 / AP: completed [csv]
[119/606] OR-020 / RA: completed [csv]
[120/606] OR-020 / Others: completed [csv]
[121/606] OR-021 / TP: completed [csv]
[122/606] OR-021 / NRM: completed [oracle_auto_reuse]
[123/606] OR-021 / FLP: error [csv]
[124/606] OR-021 / AP: completed [csv]
[125/606] OR-021 / RA: completed [csv]
[126/606] OR-021 / Others: completed [csv]
[127/606] OR-022 / TP: completed [csv]
[128/606] OR-022 / NRM: completed [oracle_auto_reuse]
[129/606] OR-022 / FLP: completed [csv]
[130/606] OR-022 / AP: completed [csv]
[131/606] OR-022 / RA: completed [csv]
[132/606] OR-022 / Others: completed [csv]
[133/606] OR-023 / TP: completed [csv]
[134/606] OR-023 / NRM: completed [oracle_auto_reuse]
[135/606] OR-023 / FLP: completed [csv]
[136/606] OR-023 / AP: completed [csv]
[137/606] OR-023 / RA: completed [csv]
[138/606] OR-023 / Others: completed [csv]
[139/606] OR-024 / TP: completed [csv]
[140/606] OR-024 / NRM: completed [oracle_auto_reuse]
[141/606] OR-024 / FLP: completed [csv]
[142/606] OR-024 / AP: completed [csv]
[143/606] OR-024 / RA: completed [csv]
[144/606] OR-024 / Others: completed [csv]
[145/606] OR-025 / TP: completed [csv]
[146/606] OR-025 / NRM: completed [oracle_auto_reuse]
[147/606] OR-025 / FLP: completed [csv]
[148/606] OR-025 / AP: completed [csv]
[149/606] OR-025 / RA: completed [csv]
[150/606] OR-025 / Others: completed [csv]
[151/606] OR-026 / TP: completed [csv]
[152/606] OR-026 / NRM: completed [oracle_auto_reuse]
[153/606] OR-026 / FLP: completed [csv]
[154/606] OR-026 / AP: completed [csv]
[155/606] OR-026 / RA: completed [csv]
[156/606] OR-026 / Others: completed [csv]
[157/606] OR-027 / TP: completed [csv]
[158/606] OR-027 / NRM: completed [oracle_auto_reuse]
[159/606] OR-027 / FLP: completed [csv]
[160/606] OR-027 / AP: completed [csv]
[161/606] OR-027 / RA: completed [csv]
[162/606] OR-027 / Others: completed [csv]
[163/606] OR-028 / TP: completed [csv]
[164/606] OR-028 / NRM: completed [oracle_auto_reuse]
[165/606] OR-028 / FLP: completed [csv]
[166/606] OR-028 / AP: completed [csv]
[167/606] OR-028 / RA: completed [csv]
[168/606] OR-028 / Others: completed [csv]
[169/606] OR-029 / TP: completed [csv]
[170/606] OR-029 / NRM: completed [oracle_auto_reuse]
[171/606] OR-029 / FLP: completed [csv]
[172/606] OR-029 / AP: completed [csv]
[173/606] OR-029 / RA: completed [csv]
[174/606] OR-029 / Others: completed [csv]
[175/606] OR-030 / TP: completed [csv]
[176/606] OR-030 / NRM: completed [oracle_auto_reuse]
[177/606] OR-030 / FLP: completed [csv]
[178/606] OR-030 / AP: completed [csv]
[179/606] OR-030 / RA: completed [csv]
[180/606] OR-030 / Others: completed [csv]
[181/606] OR-031 / TP: completed [csv]
[182/606] OR-031 / NRM: completed [oracle_auto_reuse]
[183/606] OR-031 / FLP: completed [csv]
[184/606] OR-031 / AP: completed [csv]
[185/606] OR-031 / RA: completed [csv]
[186/606] OR-031 / Others: completed [csv]
[187/606] OR-032 / TP: completed [csv]
[188/606] OR-032 / NRM: completed [oracle_auto_reuse]
[189/606] OR-032 / FLP: completed [csv]
[190/606] OR-032 / AP: completed [csv]
[191/606] OR-032 / RA: completed [csv]
[192/606] OR-032 / Others: completed [csv]
[193/606] OR-033 / TP: completed [csv]
[194/606] OR-033 / NRM: completed [oracle_auto_reuse]
[195/606] OR-033 / FLP: completed [csv]
[196/606] OR-033 / AP: completed [csv]
[197/606] OR-033 / RA: completed [csv]
[198/606] OR-033 / Others: completed [csv]
[199/606] OR-034 / TP: completed [csv]
[200/606] OR-034 / NRM: completed [oracle_auto_reuse]
[201/606] OR-034 / FLP: completed [csv]
[202/606] OR-034 / AP: error [csv]
[203/606] OR-034 / RA: completed [csv]
[204/606] OR-034 / Others: completed [csv]
[205/606] OR-035 / TP: completed [csv]
[206/606] OR-035 / NRM: completed [csv]
[207/606] OR-035 / FLP: completed [csv]
[208/606] OR-035 / AP: completed [csv]
[209/606] OR-035 / RA: completed [oracle_auto_reuse]
[210/606] OR-035 / Others: completed [csv]
[211/606] OR-036 / TP: completed [csv]
[212/606] OR-036 / NRM: completed [csv]
[213/606] OR-036 / FLP: completed [csv]
[214/606] OR-036 / AP: completed [csv]
[215/606] OR-036 / RA: completed [oracle_auto_reuse]
[216/606] OR-036 / Others: completed [csv]
[217/606] OR-037 / TP: completed [csv]
[218/606] OR-037 / NRM: completed [csv]
[219/606] OR-037 / FLP: completed [csv]
[220/606] OR-037 / AP: completed [csv]
[221/606] OR-037 / RA: completed [oracle_auto_reuse]
[222/606] OR-037 / Others: completed [csv]
[223/606] OR-038 / TP: completed [csv]
[224/606] OR-038 / NRM: completed [csv]
[225/606] OR-038 / FLP: completed [csv]
[226/606] OR-038 / AP: completed [csv]
[227/606] OR-038 / RA: completed [oracle_auto_reuse]
[228/606] OR-038 / Others: completed [csv]
[229/606] OR-039 / TP: completed [csv]
[230/606] OR-039 / NRM: error [csv]
[231/606] OR-039 / FLP: completed [csv]
[232/606] OR-039 / AP: completed [csv]
[233/606] OR-039 / RA: completed [oracle_auto_reuse]
[234/606] OR-039 / Others: completed [csv]
[235/606] OR-040 / TP: completed [csv]
[236/606] OR-040 / NRM: completed [csv]
[237/606] OR-040 / FLP: completed [csv]
[238/606] OR-040 / AP: completed [csv]
[239/606] OR-040 / RA: completed [oracle_auto_reuse]
[240/606] OR-040 / Others: completed [csv]
[241/606] OR-041 / TP: completed [csv]
[242/606] OR-041 / NRM: completed [csv]
[243/606] OR-041 / FLP: completed [csv]
[244/606] OR-041 / AP: completed [csv]
[245/606] OR-041 / RA: completed [oracle_auto_reuse]
[246/606] OR-041 / Others: completed [csv]
[247/606] OR-042 / TP: completed [csv]
[248/606] OR-042 / NRM: completed [csv]
[249/606] OR-042 / FLP: completed [csv]
[250/606] OR-042 / AP: completed [csv]
[251/606] OR-042 / RA: completed [oracle_auto_reuse]
[252/606] OR-042 / Others: completed [csv]
[253/606] OR-043 / TP: completed [csv]
[254/606] OR-043 / NRM: completed [csv]
[255/606] OR-043 / FLP: completed [csv]
[256/606] OR-043 / AP: completed [csv]
[257/606] OR-043 / RA: completed [oracle_auto_reuse]
[258/606] OR-043 / Others: completed [csv]
[259/606] OR-044 / TP: completed [csv]
[260/606] OR-044 / NRM: completed [csv]
[261/606] OR-044 / FLP: completed [csv]
[262/606] OR-044 / AP: completed [csv]
[263/606] OR-044 / RA: completed [oracle_auto_reuse]
[264/606] OR-044 / Others: completed [csv]
[265/606] OR-045 / TP: completed [csv]
[266/606] OR-045 / NRM: completed [csv]
[267/606] OR-045 / FLP: completed [csv]
[268/606] OR-045 / AP: completed [csv]
[269/606] OR-045 / RA: completed [oracle_auto_reuse]
[270/606] OR-045 / Others: completed [csv]
[271/606] OR-046 / TP: completed [csv]
[272/606] OR-046 / NRM: completed [csv]
[273/606] OR-046 / FLP: completed [csv]
[274/606] OR-046 / AP: completed [csv]
[275/606] OR-046 / RA: completed [oracle_auto_reuse]
[276/606] OR-046 / Others: completed [csv]
[277/606] OR-047 / TP: completed [csv]
[278/606] OR-047 / NRM: completed [csv]
[279/606] OR-047 / FLP: completed [csv]
[280/606] OR-047 / AP: completed [csv]
[281/606] OR-047 / RA: completed [oracle_auto_reuse]
[282/606] OR-047 / Others: completed [csv]
[283/606] OR-048 / TP: completed [csv]
[284/606] OR-048 / NRM: completed [csv]
[285/606] OR-048 / FLP: completed [csv]
[286/606] OR-048 / AP: completed [csv]
[287/606] OR-048 / RA: completed [oracle_auto_reuse]
[288/606] OR-048 / Others: completed [csv]
[289/606] OR-049 / TP: completed [csv]
[290/606] OR-049 / NRM: completed [csv]
[291/606] OR-049 / FLP: completed [csv]
[292/606] OR-049 / AP: completed [csv]
[293/606] OR-049 / RA: completed [oracle_auto_reuse]
[294/606] OR-049 / Others: completed [csv]
[295/606] OR-050 / TP: completed [csv]
[296/606] OR-050 / NRM: completed [csv]
[297/606] OR-050 / FLP: completed [csv]
[298/606] OR-050 / AP: completed [csv]
[299/606] OR-050 / RA: completed [csv]
[300/606] OR-050 / Others: completed [csv]
[301/606] OR-051 / TP: completed [csv]
[302/606] OR-051 / NRM: completed [csv]
[303/606] OR-051 / FLP: completed [csv]
[304/606] OR-051 / AP: completed [csv]
[305/606] OR-051 / RA: completed [oracle_auto_reuse]
[306/606] OR-051 / Others: completed [csv]
[307/606] OR-052 / TP: completed [csv]
[308/606] OR-052 / NRM: completed [csv]
[309/606] OR-052 / FLP: completed [csv]
[310/606] OR-052 / AP: completed [csv]
[311/606] OR-052 / RA: completed [oracle_auto_reuse]
[312/606] OR-052 / Others: completed [csv]
[313/606] OR-053 / TP: completed [csv]
[314/606] OR-053 / NRM: completed [csv]
[315/606] OR-053 / FLP: completed [csv]
[316/606] OR-053 / AP: completed [csv]
[317/606] OR-053 / RA: completed [oracle_auto_reuse]
[318/606] OR-053 / Others: completed [csv]
[319/606] OR-054 / TP: completed [csv]
[320/606] OR-054 / NRM: completed [csv]
[321/606] OR-054 / FLP: completed [csv]
[322/606] OR-054 / AP: completed [csv]
[323/606] OR-054 / RA: completed [oracle_auto_reuse]
[324/606] OR-054 / Others: completed [csv]
[325/606] OR-055 / TP: completed [csv]
[326/606] OR-055 / NRM: completed [csv]
[327/606] OR-055 / FLP: completed [csv]
[328/606] OR-055 / AP: completed [csv]
[329/606] OR-055 / RA: completed [oracle_auto_reuse]
[330/606] OR-055 / Others: completed [csv]
[331/606] OR-056 / TP: completed [csv]
[332/606] OR-056 / NRM: completed [csv]
[333/606] OR-056 / FLP: completed [csv]
[334/606] OR-056 / AP: completed [csv]
[335/606] OR-056 / RA: completed [oracle_auto_reuse]
[336/606] OR-056 / Others: completed [csv]
[337/606] OR-057 / TP: completed [csv]
[338/606] OR-057 / NRM: completed [csv]
[339/606] OR-057 / FLP: completed [csv]
[340/606] OR-057 / AP: completed [csv]
[341/606] OR-057 / RA: completed [oracle_auto_reuse]
[342/606] OR-057 / Others: completed [csv]
[343/606] OR-058 / TP: completed [csv]
[344/606] OR-058 / NRM: completed [csv]
[345/606] OR-058 / FLP: completed [oracle_auto_reuse]
[346/606] OR-058 / AP: completed [csv]
[347/606] OR-058 / RA: completed [csv]
[348/606] OR-058 / Others: completed [csv]
[349/606] OR-059 / TP: completed [csv]
[350/606] OR-059 / NRM: completed [csv]
[351/606] OR-059 / FLP: completed [oracle_auto_reuse]
[352/606] OR-059 / AP: completed [csv]
[353/606] OR-059 / RA: completed [csv]
[354/606] OR-059 / Others: completed [csv]
[355/606] OR-060 / TP: completed [csv]
[356/606] OR-060 / NRM: completed [csv]
[357/606] OR-060 / FLP: completed [oracle_auto_reuse]
[358/606] OR-060 / AP: completed [csv]
[359/606] OR-060 / RA: completed [csv]
[360/606] OR-060 / Others: completed [csv]
[361/606] OR-061 / TP: completed [csv]
[362/606] OR-061 / NRM: completed [csv]
[363/606] OR-061 / FLP: completed [oracle_auto_reuse]
[364/606] OR-061 / AP: completed [csv]
[365/606] OR-061 / RA: completed [csv]
[366/606] OR-061 / Others: completed [csv]
[367/606] OR-062 / TP: completed [csv]
[368/606] OR-062 / NRM: completed [csv]
[369/606] OR-062 / FLP: completed [oracle_auto_reuse]
[370/606] OR-062 / AP: completed [csv]
[371/606] OR-062 / RA: completed [csv]
[372/606] OR-062 / Others: completed [csv]
[373/606] OR-063 / TP: completed [csv]
[374/606] OR-063 / NRM: completed [csv]
[375/606] OR-063 / FLP: completed [oracle_auto_reuse]
[376/606] OR-063 / AP: completed [csv]
[377/606] OR-063 / RA: completed [csv]
[378/606] OR-063 / Others: completed [csv]
[379/606] OR-064 / TP: completed [csv]
[380/606] OR-064 / NRM: completed [csv]
[381/606] OR-064 / FLP: completed [oracle_auto_reuse]
[382/606] OR-064 / AP: completed [csv]
[383/606] OR-064 / RA: completed [csv]
[384/606] OR-064 / Others: completed [csv]
[385/606] OR-065 / TP: completed [csv]
[386/606] OR-065 / NRM: completed [csv]
[387/606] OR-065 / FLP: completed [oracle_auto_reuse]
[388/606] OR-065 / AP: completed [csv]
[389/606] OR-065 / RA: completed [csv]
[390/606] OR-065 / Others: completed [csv]
[391/606] OR-066 / TP: completed [csv]
[392/606] OR-066 / NRM: completed [csv]
[393/606] OR-066 / FLP: completed [oracle_auto_reuse]
[394/606] OR-066 / AP: completed [csv]
[395/606] OR-066 / RA: completed [csv]
[396/606] OR-066 / Others: completed [csv]
[397/606] OR-067 / TP: completed [csv]
[398/606] OR-067 / NRM: error [csv]
[399/606] OR-067 / FLP: completed [csv]
[400/606] OR-067 / AP: completed [oracle_auto_reuse]
[401/606] OR-067 / RA: completed [csv]
[402/606] OR-067 / Others: completed [csv]
[403/606] OR-068 / TP: completed [csv]
[404/606] OR-068 / NRM: completed [csv]
[405/606] OR-068 / FLP: error [csv]
[406/606] OR-068 / AP: completed [oracle_auto_reuse]
[407/606] OR-068 / RA: completed [csv]
[408/606] OR-068 / Others: completed [csv]
[409/606] OR-069 / TP: completed [csv]
[410/606] OR-069 / NRM: completed [csv]
[411/606] OR-069 / FLP: completed [csv]
[412/606] OR-069 / AP: completed [oracle_auto_reuse]
[413/606] OR-069 / RA: completed [csv]
[414/606] OR-069 / Others: completed [csv]
[415/606] OR-070 / TP: completed [csv]
[416/606] OR-070 / NRM: error [csv]
[417/606] OR-070 / FLP: completed [csv]
[418/606] OR-070 / AP: completed [oracle_auto_reuse]
[419/606] OR-070 / RA: completed [csv]
[420/606] OR-070 / Others: completed [csv]
[421/606] OR-071 / TP: error [csv]
[422/606] OR-071 / NRM: completed [csv]
[423/606] OR-071 / FLP: error [csv]
[424/606] OR-071 / AP: error [csv]
[425/606] OR-071 / RA: completed [csv]
[426/606] OR-071 / Others: completed [oracle_auto_reuse]
[427/606] OR-072 / TP: completed [csv]
[428/606] OR-072 / NRM: completed [csv]
[429/606] OR-072 / FLP: completed [csv]
[430/606] OR-072 / AP: completed [csv]
[431/606] OR-072 / RA: completed [csv]
[432/606] OR-072 / Others: completed [oracle_auto_reuse]
[433/606] OR-073 / TP: completed [csv]
[434/606] OR-073 / NRM: completed [csv]
[435/606] OR-073 / FLP: completed [csv]
[436/606] OR-073 / AP: completed [csv]
[437/606] OR-073 / RA: error [csv]
[438/606] OR-073 / Others: completed [oracle_auto_reuse]
[439/606] OR-074 / TP: completed [csv]
[440/606] OR-074 / NRM: completed [csv]
[441/606] OR-074 / FLP: completed [csv]
[442/606] OR-074 / AP: completed [csv]
[443/606] OR-074 / RA: completed [csv]
[444/606] OR-074 / Others: completed [oracle_auto_reuse]
[445/606] OR-075 / TP: completed [csv]
[446/606] OR-075 / NRM: completed [csv]
[447/606] OR-075 / FLP: completed [csv]
[448/606] OR-075 / AP: completed [csv]
[449/606] OR-075 / RA: completed [csv]
[450/606] OR-075 / Others: completed [oracle_auto_reuse]
[451/606] OR-076 / TP: completed [csv]
[452/606] OR-076 / NRM: completed [csv]
[453/606] OR-076 / FLP: completed [oracle_auto_reuse]
[454/606] OR-076 / AP: completed [csv]
[455/606] OR-076 / RA: completed [csv]
[456/606] OR-076 / Others: completed [csv]
[457/606] OR-077 / TP: completed [csv]
[458/606] OR-077 / NRM: completed [csv]
[459/606] OR-077 / FLP: completed [csv]
[460/606] OR-077 / AP: completed [csv]
[461/606] OR-077 / RA: completed [csv]
[462/606] OR-077 / Others: completed [oracle_auto_reuse]
[463/606] OR-078 / TP: completed [csv]
[464/606] OR-078 / NRM: completed [csv]
[465/606] OR-078 / FLP: completed [csv]
[466/606] OR-078 / AP: completed [csv]
[467/606] OR-078 / RA: completed [csv]
[468/606] OR-078 / Others: completed [oracle_auto_reuse]
[469/606] OR-079 / TP: completed [csv]
[470/606] OR-079 / NRM: completed [csv]
[471/606] OR-079 / FLP: completed [oracle_auto_reuse]
[472/606] OR-079 / AP: completed [csv]
[473/606] OR-079 / RA: completed [csv]
[474/606] OR-079 / Others: completed [csv]
[475/606] OR-080 / TP: completed [csv]
[476/606] OR-080 / NRM: completed [csv]
[477/606] OR-080 / FLP: completed [csv]

                    metric  correct  total accuracy
0  Oracle routing accuracy       92    101   91.09%
1          Solved accuracy      554    606   91.42%

Route Matrix

assigned_route,TP,NRM,FLP,AP,RA,Others
true_route,,,,,,
TP,8/9 (88.89%),9/9 (100.00%),9/9 (100.00%),7/9 (77.78%),9/9 (100.00%),9/9 (100.00%)
NRM,16/25 (64.00%),23/25 (92.00%),16/25 (64.00%),15/25 (60.00%),19/25 (76.00%),23/25 (92.00%)
FLP,14/14 (100.00%),13/14 (92.86%),14/14 (100.00%),14/14 (100.00%),12/14 (85.71%),14/14 (100.00%)
AP,5/5 (100.00%),3/5 (60.00%),4/5 (80.00%),5/5 (100.00%),4/5 (80.00%),5/5 (100.00%)
RA,19/22 (86.36%),17/22 (77.27%),14/22 (63.64%),16/22 (72.73%),21/22 (95.45%),22/22 (100.00%)
Others,16/26 (61.54%),17/26 (65.38%),16/26 (61.54%),15/26 (57.69%),16/26 (61.54%),21/26 (80.77%)

Accuracy By Route

                correct  total accuracy
assigned_route
TP                   78    101   77.23%
NRM                  82    101   81.19%
FLP                  73    101   72.28%
AP                   72    101   71.29%
RA                   81    101   80.20%
Others               94    101   93.07%

## 20. Test IndustryOR or another dataset

Choose OTHER_BENCHMARK_PATH in the setup section, then enable this cell. IndustryOR has Query and Label columns. The same runner records classification, automatically uses Others without CSV when case paths are absent, and executes the generated program. A dataset with case CSV paths uses the corresponding classified route instead.

In [124]:
RUN_OTHER_DATASET = False
if RUN_OTHER_DATASET:
    other_results = run_test(OTHER_BENCHMARK_PATH, output_csv=RESULTS_DIR / "other/results.csv")
    report_results(other_results, RESULTS_DIR / "other")